# Numerai v5.2 — Selection + PCA500 + Lag1/Lag2 + Ridge/ElasticNet/XGBoost Stacking

이 노트북은 기존 Ridge + ElasticNet 전체 파이프라인의 구조와 변수명을 최대한 유지하면서 XGBoost를 추가합니다.

파이프라인:

1. `v5.2/features.json`, `train.parquet`, `validation.parquet` 다운로드
2. 전체 feature 중 target 절대상관계수 상위 50% 선택
3. `StandardScaler + IncrementalPCA(500)` 학습 및 저장
4. `PCA500 + era 평균 lag1 + lag2` 생성
5. 내부 데이터에서 Ridge + ElasticNet + XGBoost 학습
6. 세 모델의 era별 rank를 입력으로 `Ridge(alpha=1.0)` 메타모델 학습
7. OOS 검증 후 기본 모델을 전체 내부 데이터로 재학습
8. 공식 `validation.parquet`을 동일하게 변환
9. Numerai Diagnostics용 `id,prediction` CSV 생성

중요:
- 기존 전처리 결과와 맞추기 위해 `VERSION = "v5.2"`, `TARGET_COL = "target"`로 고정합니다.
- Ridge와 ElasticNet에는 모델 입력용 StandardScaler를 적용합니다.
- XGBoost는 같은 1,500개 feature를 사용하지만 트리 모델이므로 별도 scaling 없이 학습합니다.
- XGBoost 하이퍼파라미터는 기존 Optuna 1차 탐색 최적값을 사용합니다.

In [2]:
# 필요한 패키지 설치 — Jupyter/Colab에서 한 번만 실행
# Colab의 pandas 고정 버전 충돌을 피하기 위해 pandas는 강제 업그레이드하지 않습니다.
%pip install -q numerapi pyarrow scikit-learn scipy joblib cloudpickle numerai-tools xgboost

Note: you may need to restart the kernel to use updated packages.

In [3]:
# ============================================
# 0. 라이브러리 / 경로 / 공통 설정
# ============================================
import gc
import json
import os
import random
import shutil
import subprocess
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.parquet as pq
import xgboost as xgb

from numerapi import NumerAPI
from numerai_tools.scoring import numerai_corr
from sklearn.decomposition import IncrementalPCA
from sklearn.linear_model import Ridge, SGDRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler

SEED = 42
random.seed(SEED)
np.random.seed(SEED)

VERSION = "v5.2"
TARGET_COL = "target"
PCA_N = 500
LAGS = (1, 2)

SELECTION_BATCH_SIZE = 20_000
PCA_FIT_BATCH_SIZE = 50_000
TRANSFORM_BATCH_SIZE = 20_000
MODEL_BATCH_SIZE = 50_000

# 기존 Mac 로컬 경로를 그대로 사용합니다.
# Colab Drive를 쓸 경우 이 한 줄만 Drive 경로로 바꾸면 됩니다.
BASE_DIR = Path(
    "/Users/seomichelle/26-1 ESAA:Python/datasets/Numerai"
)

DATA_DIR = BASE_DIR / VERSION
PREPROCESS_DIR = BASE_DIR / "numerai_postprocess_v52"
CACHE_DIR = BASE_DIR / "cache_v52"
MODEL_DIR = BASE_DIR / "ridge_elastic_xgboost_stack_v52"
DIAGNOSTICS_DIR = BASE_DIR / "diagnostics_v52"
MEMMAP_DIR = MODEL_DIR / "memmap"

for directory in [
    DATA_DIR,
    PREPROCESS_DIR,
    CACHE_DIR,
    MODEL_DIR,
    DIAGNOSTICS_DIR,
    MEMMAP_DIR,
]:
    directory.mkdir(parents=True, exist_ok=True)

FEATURES_JSON_PATH = DATA_DIR / "features.json"
TRAIN_PATH = DATA_DIR / "train.parquet"
VALIDATION_PATH = DATA_DIR / "validation.parquet"

TRAIN_PCA_ALL_PATH = CACHE_DIR / "train_pca_all.parquet"
TRAIN_FINAL_PATH = CACHE_DIR / "train_final_cache.parquet"
VAL_FINAL_PATH = CACHE_DIR / "val_final_cache.parquet"
LEGACY_MODEL_DATA_PATH = BASE_DIR / "pca500_lag1_lag2.parquet"

VALIDATION_PCA_ALL_PATH = CACHE_DIR / "validation_pca_all.parquet"
VALIDATION_FINAL_PATH = CACHE_DIR / "validation_pca500_lag1_lag2.parquet"


def detect_xgb_device():
    # NVIDIA GPU가 실제로 보이면 cuda, 아니면 cpu를 사용합니다.
    try:
        result = subprocess.run(
            ["nvidia-smi"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            check=False,
        )
        return "cuda" if result.returncode == 0 else "cpu"
    except FileNotFoundError:
        return "cpu"


XGB_DEVICE = detect_xgb_device()

print("BASE_DIR:", BASE_DIR)
print("VERSION:", VERSION)
print("XGBoost device:", XGB_DEVICE)

BASE_DIR: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai
VERSION: v5.2
XGBoost device: cpu

In [4]:
# ============================================
# 1. 데이터 다운로드
# ============================================
napi = NumerAPI()


def download_with_retry(filename, max_retries=5):
    target = BASE_DIR / filename
    target.parent.mkdir(parents=True, exist_ok=True)

    if target.exists():
        print("이미 존재:", target)
        return target

    for attempt in range(1, max_retries + 1):
        try:
            print(f"다운로드 {attempt}/{max_retries}: {filename}")
            napi.download_dataset(filename, dest_path=str(target))
            return target
        except Exception as error:
            print("다운로드 실패:", error)
            if attempt == max_retries:
                raise


for filename in [
    f"{VERSION}/features.json",
    f"{VERSION}/train.parquet",
    f"{VERSION}/validation.parquet",
]:
    download_with_retry(filename)

print("features.json:", FEATURES_JSON_PATH.exists())
print("train.parquet:", TRAIN_PATH.exists())
print("validation.parquet:", VALIDATION_PATH.exists())

이미 존재: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/v5.2/features.json
이미 존재: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/v5.2/train.parquet
이미 존재: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/v5.2/validation.parquet
features.json: True
train.parquet: True
validation.parquet: True

In [5]:
# ============================================
# 2. 공용 스트리밍 유틸
# ============================================
def clean_array(arr):
    return np.nan_to_num(
        arr,
        nan=0.0,
        posinf=0.0,
        neginf=0.0,
    )


def get_schema_names(path):
    return pq.ParquetFile(path).schema_arrow.names


def resolve_id_storage_column(path):
    names = get_schema_names(path)

    if "id" in names:
        return "id"
    if "__index_level_0__" in names:
        return "__index_level_0__"

    return None


def normalize_id_column(chunk):
    if "id" in chunk.columns:
        return chunk
    if "__index_level_0__" in chunk.columns:
        return chunk.rename(columns={"__index_level_0__": "id"})
    if chunk.index.name == "id":
        return chunk.reset_index()

    raise ValueError(
        "id를 찾지 못했습니다. "
        f"columns={chunk.columns.tolist()[:10]}, index={chunk.index.name}"
    )


def iter_parquet_batches(path, columns, batch_size):
    pf = pq.ParquetFile(path)
    available = set(pf.schema_arrow.names)

    requested = []
    for column in columns:
        if column in available and column not in requested:
            requested.append(column)

    id_storage = resolve_id_storage_column(path)
    if "id" in columns and id_storage is not None and id_storage not in requested:
        requested.insert(0, id_storage)

    for batch in pf.iter_batches(
        columns=requested,
        batch_size=batch_size,
    ):
        chunk = batch.to_pandas()

        if "id" in columns:
            chunk = normalize_id_column(chunk)

        if "era" in chunk.columns:
            chunk["era"] = chunk["era"].astype(int)

        yield chunk


def remove_if_exists(path):
    path = Path(path)
    if path.exists():
        path.unlink()


def append_parquet_batch(writer, frame):
    # id를 pandas index로 저장하여 기존 캐시 구조를 유지합니다.
    frame = frame.set_index("id")
    table = pa.Table.from_pandas(frame, preserve_index=True)

    if writer["object"] is None:
        writer["object"] = pq.ParquetWriter(
            str(writer["path"]),
            table.schema,
            compression="snappy",
        )

    writer["object"].write_table(table)


def close_writer(writer):
    if writer["object"] is not None:
        writer["object"].close()
        writer["object"] = None

In [6]:
# ============================================
# 3. Feature Selection
# 전체 all feature 중 |corr(feature, target)| 상위 50%
# ============================================
with open(FEATURES_JSON_PATH, "r", encoding="utf-8") as file:
    feature_metadata = json.load(file)

all_feature_cols = feature_metadata["feature_sets"]["all"]
print("전체 feature 수:", len(all_feature_cols))

SELECTED_FEATURES_PATH = PREPROCESS_DIR / "selected_features.json"

if SELECTED_FEATURES_PATH.exists():
    with open(SELECTED_FEATURES_PATH, "r", encoding="utf-8") as file:
        selected_features = json.load(file)

    print("기존 selected_features 로드:", len(selected_features))

else:
    p = len(all_feature_cols)

    sum_x = np.zeros(p, dtype=np.float64)
    sum_x2 = np.zeros(p, dtype=np.float64)
    sum_xy = np.zeros(p, dtype=np.float64)
    sum_y = 0.0
    sum_y2 = 0.0
    n_total = 0

    selection_columns = all_feature_cols + [TARGET_COL]

    for chunk in iter_parquet_batches(
        TRAIN_PATH,
        selection_columns,
        SELECTION_BATCH_SIZE,
    ):
        chunk = chunk[chunk[TARGET_COL].notna()].copy()
        if chunk.empty:
            continue

        X_chunk = clean_array(
            chunk[all_feature_cols].to_numpy(dtype=np.float32)
        )
        y_chunk = clean_array(
            chunk[TARGET_COL].to_numpy(dtype=np.float32)
        )

        n_chunk = len(y_chunk)
        n_total += n_chunk

        sum_x += X_chunk.sum(axis=0, dtype=np.float64)
        sum_x2 += (X_chunk * X_chunk).sum(axis=0, dtype=np.float64)
        sum_xy += X_chunk.T @ y_chunk.astype(np.float64)
        sum_y += y_chunk.sum(dtype=np.float64)
        sum_y2 += (y_chunk * y_chunk).sum(dtype=np.float64)

        print(f"Feature selection: {n_total:,} rows")

    cov_xy = sum_xy - (sum_x * sum_y / n_total)
    var_x = sum_x2 - (sum_x ** 2 / n_total)
    var_y = sum_y2 - (sum_y ** 2 / n_total)

    corr = cov_xy / (np.sqrt(var_x * var_y) + 1e-12)
    corr = np.nan_to_num(corr, nan=0.0, posinf=0.0, neginf=0.0)

    scores = np.abs(corr)
    threshold = np.median(scores)

    selected_features = [
        feature
        for feature, score in zip(all_feature_cols, scores)
        if score >= threshold
    ]

    with open(SELECTED_FEATURES_PATH, "w", encoding="utf-8") as file:
        json.dump(selected_features, file, ensure_ascii=False, indent=2)

    print("selected_features 저장:", SELECTED_FEATURES_PATH)

print("선택된 feature 수:", len(selected_features))

if VERSION == "v5.2" and len(selected_features) != 1374:
    print("주의: 기존 v5.2 결과는 1,374개였습니다.")

전체 feature 수: 2748
기존 selected_features 로드: 1374
선택된 feature 수: 1374

In [7]:
# ============================================
# 4. Raw StandardScaler + IncrementalPCA(500)
# ============================================
RAW_SCALER_PATH = PREPROCESS_DIR / "fitted_scaler.joblib"
PCA_PATH = PREPROCESS_DIR / "fitted_pca.joblib"

if RAW_SCALER_PATH.exists() and PCA_PATH.exists():
    raw_scaler = joblib.load(RAW_SCALER_PATH)
    pca = joblib.load(PCA_PATH)
    print("기존 scaler / PCA 로드 완료")

else:
    fit_columns = selected_features

    raw_scaler = StandardScaler()
    processed = 0

    for chunk in iter_parquet_batches(
        TRAIN_PATH,
        fit_columns,
        PCA_FIT_BATCH_SIZE,
    ):
        X_chunk = clean_array(
            chunk[selected_features].to_numpy(dtype=np.float32)
        )
        raw_scaler.partial_fit(X_chunk)
        processed += len(chunk)
        print(f"[Raw Scaler] {processed:,} rows")

    pca_n = min(PCA_N, len(selected_features))
    pca = IncrementalPCA(
        n_components=pca_n,
        batch_size=PCA_FIT_BATCH_SIZE,
    )

    processed = 0
    fitted_batches = 0

    for chunk in iter_parquet_batches(
        TRAIN_PATH,
        fit_columns,
        PCA_FIT_BATCH_SIZE,
    ):
        X_chunk = clean_array(
            chunk[selected_features].to_numpy(dtype=np.float32)
        )
        X_scaled = raw_scaler.transform(X_chunk)

        if X_scaled.shape[0] >= pca_n:
            pca.partial_fit(X_scaled)
            fitted_batches += 1

        processed += len(chunk)
        print(f"[PCA] {processed:,} rows")

    if fitted_batches == 0:
        raise RuntimeError("PCA가 한 번도 fit되지 않았습니다.")

    joblib.dump(raw_scaler, RAW_SCALER_PATH)
    joblib.dump(pca, PCA_PATH)

    print("raw scaler 저장:", RAW_SCALER_PATH)
    print("PCA 저장:", PCA_PATH)

print("selected feature 수:", len(selected_features))
print("raw scaler 입력 수:", raw_scaler.n_features_in_)
print("PCA 입력 수:", pca.n_features_in_)
print("PCA component 수:", pca.n_components_)
print("설명분산 비율 합:", pca.explained_variance_ratio_.sum())

assert len(selected_features) == raw_scaler.n_features_in_
assert len(selected_features) == pca.n_features_in_
assert pca.n_components_ == PCA_N

기존 scaler / PCA 로드 완료
selected feature 수: 1374
raw scaler 입력 수: 1374
PCA 입력 수: 1374
PCA component 수: 500
설명분산 비율 합: 0.9041530365450252

In [8]:
# ============================================
# 5. 원본 데이터 → PCA500 변환
# ============================================
pca_cols = [f"pca_{i}" for i in range(PCA_N)]


def transform_source_to_pca(
    source_path,
    output_path,
    filter_validation=False,
):
    remove_if_exists(output_path)
    writer = {"path": Path(output_path), "object": None}

    columns = ["id", "era", TARGET_COL] + selected_features
    if filter_validation:
        columns.insert(2, "data_type")

    processed = 0

    try:
        for chunk in iter_parquet_batches(
            source_path,
            columns,
            TRANSFORM_BATCH_SIZE,
        ):
            if filter_validation:
                chunk = chunk[chunk["data_type"] == "validation"].copy()
                if chunk.empty:
                    continue

            X_raw = clean_array(
                chunk[selected_features].to_numpy(dtype=np.float32)
            )
            X_scaled = raw_scaler.transform(X_raw)
            X_pca = pca.transform(X_scaled).astype(np.float32)

            out = pd.DataFrame(X_pca, columns=pca_cols)
            out["era"] = chunk["era"].to_numpy(dtype=np.int32)
            out[TARGET_COL] = chunk[TARGET_COL].to_numpy(dtype=np.float32)
            out["id"] = chunk["id"].astype(str).to_numpy()
            out = out[["id"] + pca_cols + ["era", TARGET_COL]]

            append_parquet_batch(writer, out)
            processed += len(out)
            print(f"PCA 변환: {processed:,} rows")

    finally:
        close_writer(writer)

    print("저장 완료:", output_path)


if not TRAIN_PCA_ALL_PATH.exists():
    transform_source_to_pca(
        TRAIN_PATH,
        TRAIN_PCA_ALL_PATH,
        filter_validation=False,
    )
else:
    print("기존 파일 사용:", TRAIN_PCA_ALL_PATH)

기존 파일 사용: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/cache_v52/train_pca_all.parquet

In [9]:
# ============================================
# 6. Era split + era 평균 lag1/lag2
# train_final_cache / val_final_cache 생성
# ============================================
def compute_era_means(pca_path):
    sums = {}
    counts = {}

    for chunk in iter_parquet_batches(
        pca_path,
        ["era"] + pca_cols,
        TRANSFORM_BATCH_SIZE,
    ):
        era_array = chunk["era"].to_numpy(dtype=np.int32)
        X = chunk[pca_cols].to_numpy(dtype=np.float32)

        for era in np.unique(era_array):
            mask = era_array == era
            current_sum = X[mask].sum(axis=0, dtype=np.float64)
            current_count = int(mask.sum())

            if int(era) not in sums:
                sums[int(era)] = current_sum
                counts[int(era)] = current_count
            else:
                sums[int(era)] += current_sum
                counts[int(era)] += current_count

    eras = sorted(sums)
    means = np.vstack([
        sums[era] / counts[era]
        for era in eras
    ]).astype(np.float32)

    return pd.DataFrame(means, index=eras, columns=pca_cols)


def make_lag_lookup(era_mean_df, era_subset):
    subset = era_mean_df.loc[sorted(era_subset)].copy()

    lag1 = subset.shift(1).fillna(0)
    lag2 = subset.shift(2).fillna(0)

    lag1_lookup = {
        int(era): row.to_numpy(dtype=np.float32)
        for era, row in lag1.iterrows()
    }
    lag2_lookup = {
        int(era): row.to_numpy(dtype=np.float32)
        for era, row in lag2.iterrows()
    }

    return lag1_lookup, lag2_lookup


era_mean_df = compute_era_means(TRAIN_PCA_ALL_PATH)
unique_eras = sorted(era_mean_df.index.astype(int).tolist())

split_point = int(len(unique_eras) * 0.8)
train_eras = set(unique_eras[:split_point])
valid_eras = set(unique_eras[split_point:])

print("전체 era:", len(unique_eras))
print("train era:", len(train_eras), min(train_eras), "~", max(train_eras))
print("valid era:", len(valid_eras), min(valid_eras), "~", max(valid_eras))

train_lag1, train_lag2 = make_lag_lookup(era_mean_df, train_eras)
valid_lag1, valid_lag2 = make_lag_lookup(era_mean_df, valid_eras)

lag1_cols = [f"{column}_lag1" for column in pca_cols]
lag2_cols = [f"{column}_lag2" for column in pca_cols]
FEATURES = pca_cols + lag1_cols + lag2_cols

remove_if_exists(TRAIN_FINAL_PATH)
remove_if_exists(VAL_FINAL_PATH)

train_writer = {"path": TRAIN_FINAL_PATH, "object": None}
valid_writer = {"path": VAL_FINAL_PATH, "object": None}

train_rows = 0
valid_rows = 0

try:
    for chunk in iter_parquet_batches(
        TRAIN_PCA_ALL_PATH,
        ["id", "era", TARGET_COL] + pca_cols,
        TRANSFORM_BATCH_SIZE,
    ):
        for era_set, lag1_lookup, lag2_lookup, writer_name in [
            (train_eras, train_lag1, train_lag2, "train"),
            (valid_eras, valid_lag1, valid_lag2, "valid"),
        ]:
            sub = chunk[chunk["era"].isin(era_set)].copy()
            if sub.empty:
                continue

            era_array = sub["era"].to_numpy(dtype=np.int32)
            lag1_array = np.vstack([
                lag1_lookup[int(era)]
                for era in era_array
            ])
            lag2_array = np.vstack([
                lag2_lookup[int(era)]
                for era in era_array
            ])

            final = pd.concat(
                [
                    sub[["id"] + pca_cols].reset_index(drop=True),
                    pd.DataFrame(lag1_array, columns=lag1_cols),
                    pd.DataFrame(lag2_array, columns=lag2_cols),
                ],
                axis=1,
            )

            final["era"] = era_array
            final[TARGET_COL] = sub[TARGET_COL].to_numpy(dtype=np.float32)
            final = final[["id"] + FEATURES + ["era", TARGET_COL]]

            if writer_name == "train":
                append_parquet_batch(train_writer, final)
                train_rows += len(final)
            else:
                append_parquet_batch(valid_writer, final)
                valid_rows += len(final)

        print(f"cache 생성: train={train_rows:,}, valid={valid_rows:,}")

finally:
    close_writer(train_writer)
    close_writer(valid_writer)

# 기존 모델 노트북이 사용한 이름을 그대로 생성합니다.
shutil.copy2(VAL_FINAL_PATH, LEGACY_MODEL_DATA_PATH)

print("train_final_cache:", TRAIN_FINAL_PATH)
print("val_final_cache:", VAL_FINAL_PATH)
print("pca500_lag1_lag2:", LEGACY_MODEL_DATA_PATH)

전체 era: 574
train era: 459 1 ~ 459
valid era: 115 460 ~ 574
cache 생성: train=20,000, valid=0
cache 생성: train=40,000, valid=0
cache 생성: train=60,000, valid=0
cache 생성: train=80,000, valid=0
cache 생성: train=100,000, valid=0
cache 생성: train=120,000, valid=0
cache 생성: train=140,000, valid=0
cache 생성: train=160,000, valid=0
cache 생성: train=180,000, valid=0
cache 생성: train=200,000, valid=0
cache 생성: train=220,000, valid=0
cache 생성: train=240,000, valid=0
cache 생성: train=260,000, valid=0
cache 생성: train=280,000, valid=0
cache 생성: train=300,000, valid=0
cache 생성: train=320,000, valid=0
cache 생성: train=340,000, valid=0
cache 생성: train=360,000, valid=0
cache 생성: train=380,000, valid=0
cache 생성: train=400,000, valid=0
cache 생성: train=420,000, valid=0
cache 생성: train=440,000, valid=0
cache 생성: train=460,000, valid=0
cache 생성: train=480,000, valid=0
cache 생성: train=500,000, valid=0
cache 생성: train=520,000, valid=0
cache 생성: train=540,000, valid=0
cache 생성: train=560,000, valid=0
cache 생성: train=580,000, valid=0
cache 생성: train=600,000, valid=0
cache 생성: train=620,000, valid=0
cache 생성: train=640,000, valid=0
cache 생성: train=660,000, valid=0
cache 생성: train=680,000, valid=0
cache 생성: train=700,000, valid=0
cache 생성: train=720,000, valid=0
cache 생성: train=740,000, valid=0
cache 생성: train=760,000, valid=0
cache 생성: train=780,000, valid=0
cache 생성: train=800,000, valid=0
cache 생성: train=820,000, valid=0
cache 생성: train=840,000, valid=0
cache 생성: train=860,000, valid=0
cache 생성: train=880,000, valid=0
cache 생성: train=900,000, valid=0
cache 생성: train=920,000, valid=0
cache 생성: train=940,000, valid=0
cache 생성: train=960,000, valid=0
cache 생성: train=980,000, valid=0
cache 생성: train=1,000,000, valid=0
cache 생성: train=1,020,000, valid=0
cache 생성: train=1,040,000, valid=0
cache 생성: train=1,060,000, valid=0
cache 생성: train=1,080,000, valid=0
cache 생성: train=1,100,000, valid=0
cache 생성: train=1,120,000, valid=0
cache 생성: train=1,140,000, valid=0
cache 생성: train=1,160,000, valid=0
cache 생성: train=1,180,000, valid=0
cache 생성: train=1,200,000, valid=0
cache 생성: train=1,220,000, valid=0
cache 생성: train=1,240,000, valid=0
cache 생성: train=1,260,000, valid=0
cache 생성: train=1,280,000, valid=0
cache 생성: train=1,300,000, valid=0
cache 생성: train=1,320,000, valid=0
cache 생성: train=1,340,000, valid=0
cache 생성: train=1,360,000, valid=0
cache 생성: train=1,380,000, valid=0
cache 생성: train=1,400,000, valid=0
cache 생성: train=1,420,000, valid=0
cache 생성: train=1,440,000, valid=0
cache 생성: train=1,460,000, valid=0
cache 생성: train=1,480,000, valid=0
cache 생성: train=1,500,000, valid=0
cache 생성: train=1,520,000, valid=0
cache 생성: train=1,540,000, valid=0
cache 생성: train=1,560,000, valid=0
cache 생성: train=1,580,000, valid=0
cache 생성: train=1,600,000, valid=0
cache 생성: train=1,620,000, valid=0
cache 생성: train=1,640,000, valid=0
cache 생성: train=1,660,000, valid=0
cache 생성: train=1,680,000, valid=0
cache 생성: train=1,700,000, valid=0
cache 생성: train=1,720,000, valid=0
cache 생성: train=1,740,000, valid=0
cache 생성: train=1,760,000, valid=0
cache 생성: train=1,780,000, valid=0
cache 생성: train=1,800,000, valid=0
cache 생성: train=1,820,000, valid=0
cache 생성: train=1,840,000, valid=0
cache 생성: train=1,860,000, valid=0
cache 생성: train=1,880,000, valid=0
cache 생성: train=1,900,000, valid=0
cache 생성: train=1,920,000, valid=0
cache 생성: train=1,940,000, valid=0
cache 생성: train=1,960,000, valid=0
cache 생성: train=1,980,000, valid=0
cache 생성: train=2,000,000, valid=0
cache 생성: train=2,020,000, valid=0
cache 생성: train=2,040,000, valid=0
cache 생성: train=2,060,000, valid=0
cache 생성: train=2,080,000, valid=0
cache 생성: train=2,100,000, valid=0
cache 생성: train=2,120,000, valid=0
cache 생성: train=2,140,000, valid=0
cache 생성: train=2,158,685, valid=1,315
cache 생성: train=2,158,685, valid=21,315
cache 생성: train=2,158,685, valid=41,315
cache 생성: train=2,158,685, valid=61,315
cache 생성: train=2,158,685, valid=81,315
cache 생성: train=2,158,685, valid=101,315
cache 생성: train=2,158,685, valid=121,315
cache 생성: train=2,158,685, valid=141,315
cache 생성: train=2,158,685, valid=161,315
cache 생성: train=2,158,685, valid=181,315
cache 생성: train=2,158,685, valid=201,315
cache 생성: train=2,158,685, valid=221,315
cache 생성: train=2,158,685, valid=241,315
cache 생성: train=2,158,685, valid=261,315
cache 생성: train=2,158,685, valid=281,315
cache 생성: train=2,158,685, valid=301,315
cache 생성: train=2,158,685, valid=321,315
cache 생성: train=2,158,685, valid=341,315
cache 생성: train=2,158,685, valid=361,315
cache 생성: train=2,158,685, valid=381,315
cache 생성: train=2,158,685, valid=401,315
cache 생성: train=2,158,685, valid=421,315
cache 생성: train=2,158,685, valid=441,315
cache 생성: train=2,158,685, valid=461,315
cache 생성: train=2,158,685, valid=481,315
cache 생성: train=2,158,685, valid=501,315
cache 생성: train=2,158,685, valid=521,315
cache 생성: train=2,158,685, valid=541,315
cache 생성: train=2,158,685, valid=561,315
cache 생성: train=2,158,685, valid=581,315
cache 생성: train=2,158,685, valid=587,583
train_final_cache: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/cache_v52/train_final_cache.parquet
val_final_cache: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/cache_v52/val_final_cache.parquet
pca500_lag1_lag2: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/pca500_lag1_lag2.parquet

In [10]:
# ============================================
# 7. 캐시 구조 확인
# ============================================
train_final_check = pd.read_parquet(
    TRAIN_FINAL_PATH,
    columns=["era", TARGET_COL],
)
val_final_check = pd.read_parquet(
    VAL_FINAL_PATH,
    columns=["era", TARGET_COL],
)

print(
    "train_final shape:",
    pq.ParquetFile(TRAIN_FINAL_PATH).metadata.num_rows,
    "rows",
)
print(
    "val_final shape:",
    pq.ParquetFile(VAL_FINAL_PATH).metadata.num_rows,
    "rows",
)
print("train era:", train_final_check["era"].min(), "~", train_final_check["era"].max())
print("valid era:", val_final_check["era"].min(), "~", val_final_check["era"].max())

sample = pd.read_parquet(VAL_FINAL_PATH).head()
print("id index name:", sample.index.name)
print("feature 수:", len(FEATURES))
print("뒤 컬럼:", sample.columns[-10:].tolist())

assert sample.index.name == "id"
assert len(FEATURES) == 1500

# 확인용 객체는 메모리에서 제거합니다.
del train_final_check, val_final_check, sample
gc.collect()

train_final shape: 2158685 rows
val_final shape: 587583 rows
train era: 1 ~ 459
valid era: 460 ~ 574
id index name: id
feature 수: 1500
뒤 컬럼: ['pca_492_lag2', 'pca_493_lag2', 'pca_494_lag2', 'pca_495_lag2', 'pca_496_lag2', 'pca_497_lag2', 'pca_498_lag2', 'pca_499_lag2', 'era', 'target']

0

In [11]:
# ============================================
# 8. Ridge / ElasticNet / XGBoost 내부 학습 데이터 준비
# 기존 코드와 동일하게 587,583행 데이터 사용
# ============================================
model_df = pd.read_parquet(LEGACY_MODEL_DATA_PATH)

model_df[FEATURES] = (
    model_df[FEATURES]
    .replace([np.inf, -np.inf], np.nan)
    .fillna(0)
    .astype(np.float32)
)
model_df[TARGET_COL] = model_df[TARGET_COL].astype(np.float32)
model_df = model_df[model_df[TARGET_COL].notna()].copy()

internal_eras = sorted(model_df["era"].unique())
internal_split = int(len(internal_eras) * 0.8)

internal_train_eras = internal_eras[:internal_split]
internal_valid_eras = internal_eras[internal_split:]

train_df = (
    model_df[model_df["era"].isin(internal_train_eras)]
    .reset_index()
)
valid_df = (
    model_df[model_df["era"].isin(internal_valid_eras)]
    .reset_index()
)

X_train = train_df[FEATURES].to_numpy(dtype=np.float32)
y_train_arr = train_df[TARGET_COL].to_numpy(dtype=np.float32)

X_valid = valid_df[FEATURES].to_numpy(dtype=np.float32)
y_valid_arr = valid_df[TARGET_COL].to_numpy(dtype=np.float32)

val_era_arr = valid_df["era"].to_numpy(dtype=np.int32)
val_id_arr = valid_df["id"].astype(str).to_numpy()

print("전체 era:", len(internal_eras))
print("train era:", min(internal_train_eras), "~", max(internal_train_eras))
print("valid era:", min(internal_valid_eras), "~", max(internal_valid_eras))
print("X_train:", X_train.shape)
print("X_valid:", X_valid.shape)

# 필요한 배열만 남겨 메모리를 확보합니다.
del train_df, valid_df, model_df
gc.collect()

전체 era: 115
train era: 460 ~ 551
valid era: 552 ~ 574
X_train: (461940, 1500)
X_valid: (125643, 1500)

0

In [12]:
# ============================================
# 9. 모델 입력용 Scaling
# Ridge / ElasticNet만 scaling하고 XGBoost는 원본 1,500개 feature 사용
# ============================================
model_scaler = StandardScaler()

for start in range(0, X_train.shape[0], MODEL_BATCH_SIZE):
    end = min(start + MODEL_BATCH_SIZE, X_train.shape[0])
    model_scaler.partial_fit(X_train[start:end])
    print(f"Model scaler fit: {end:,}/{X_train.shape[0]:,}")

X_TRAIN_SCALED_PATH = MEMMAP_DIR / "X_train_scaled.dat"
X_VALID_SCALED_PATH = MEMMAP_DIR / "X_valid_scaled.dat"

X_train_scaled = np.memmap(
    X_TRAIN_SCALED_PATH,
    dtype="float32",
    mode="w+",
    shape=X_train.shape,
)
X_valid_scaled = np.memmap(
    X_VALID_SCALED_PATH,
    dtype="float32",
    mode="w+",
    shape=X_valid.shape,
)

for start in range(0, X_train.shape[0], MODEL_BATCH_SIZE):
    end = min(start + MODEL_BATCH_SIZE, X_train.shape[0])
    X_train_scaled[start:end] = model_scaler.transform(
        X_train[start:end]
    ).astype(np.float32)
    print(f"X_train scaling: {end:,}/{X_train.shape[0]:,}")

for start in range(0, X_valid.shape[0], MODEL_BATCH_SIZE):
    end = min(start + MODEL_BATCH_SIZE, X_valid.shape[0])
    X_valid_scaled[start:end] = model_scaler.transform(
        X_valid[start:end]
    ).astype(np.float32)
    print(f"X_valid scaling: {end:,}/{X_valid.shape[0]:,}")

X_train_scaled.flush()
X_valid_scaled.flush()

joblib.dump(model_scaler, MODEL_DIR / "model_input_scaler.joblib")
print("model scaler 저장 완료")

Model scaler fit: 50,000/461,940
Model scaler fit: 100,000/461,940
Model scaler fit: 150,000/461,940
Model scaler fit: 200,000/461,940
Model scaler fit: 250,000/461,940
Model scaler fit: 300,000/461,940
Model scaler fit: 350,000/461,940
Model scaler fit: 400,000/461,940
Model scaler fit: 450,000/461,940
Model scaler fit: 461,940/461,940
X_train scaling: 50,000/461,940
X_train scaling: 100,000/461,940
X_train scaling: 150,000/461,940
X_train scaling: 200,000/461,940
X_train scaling: 250,000/461,940
X_train scaling: 300,000/461,940
X_train scaling: 350,000/461,940
X_train scaling: 400,000/461,940
X_train scaling: 450,000/461,940
X_train scaling: 461,940/461,940
X_valid scaling: 50,000/125,643
X_valid scaling: 100,000/125,643
X_valid scaling: 125,643/125,643
model scaler 저장 완료

In [13]:
# ============================================
# 10. 평가 함수
# ============================================
def simple_per_era_corr(era_arr, target_arr, pred_arr):
    eval_df = pd.DataFrame({
        "era": era_arr,
        "target": target_arr,
        "prediction": pred_arr,
    })

    def era_corr(sub):
        return np.corrcoef(
            sub["prediction"].rank(pct=True),
            sub["target"],
        )[0, 1]

    try:
        return eval_df.groupby("era").apply(
            era_corr,
            include_groups=False,
        )
    except TypeError:
        # pandas 구버전 호환
        return eval_df.groupby("era").apply(era_corr)


def evaluate_prediction(name, prediction):
    prediction = np.asarray(prediction).reshape(-1)

    corr = simple_per_era_corr(
        val_era_arr,
        y_valid_arr,
        prediction,
    )

    mean_corr = corr.mean()
    std_corr = corr.std(ddof=0)
    sharpe = mean_corr / std_corr if std_corr > 0 else np.nan

    rmse = np.sqrt(mean_squared_error(y_valid_arr, prediction))
    mae = mean_absolute_error(y_valid_arr, prediction)

    print()
    print(f"========== {name} Validation Result ==========")
    print(f"RMSE: {rmse:.6f}")
    print(f"MAE: {mae:.6f}")
    print(f"per-era CORR mean: {mean_corr:.6f}")
    print(f"per-era CORR std:  {std_corr:.6f}")
    print(f"Sharpe:            {sharpe:.6f}")
    print("================================================")

    return {
        "model": name,
        "rmse": rmse,
        "mae": mae,
        "mean_corr": mean_corr,
        "std_corr": std_corr,
        "sharpe": sharpe,
    }

In [14]:
# ============================================
# 11. Base Ridge + ElasticNet + XGBoost 학습
# ============================================
# Ridge — 기존 탐색 결과에서 가장 높은 Sharpe를 보인 alpha
BASE_RIDGE_ALPHA = 3_000_000

base_ridge_model = Ridge(
    alpha=BASE_RIDGE_ALPHA,
    fit_intercept=True,
    solver="lsqr",
    max_iter=5000,
    tol=1e-4,
)
base_ridge_model.fit(X_train_scaled, y_train_arr)
ridge_pred = base_ridge_model.predict(X_valid_scaled).astype(np.float32)


# ElasticNet — 기존 코드와 동일한 SGDRegressor 방식
base_elastic_model = SGDRegressor(
    loss="squared_error",
    penalty="elasticnet",
    alpha=1e-3,
    l1_ratio=0.03,
    learning_rate="invscaling",
    eta0=0.001,
    power_t=0.5,
    max_iter=1,
    tol=None,
    random_state=SEED,
    average=True,
)

ELASTIC_EPOCHS = 20
rng = np.random.default_rng(SEED)

for epoch in range(ELASTIC_EPOCHS):
    indices = rng.permutation(X_train_scaled.shape[0])

    for start in range(0, len(indices), MODEL_BATCH_SIZE):
        end = min(start + MODEL_BATCH_SIZE, len(indices))
        idx = indices[start:end]

        base_elastic_model.partial_fit(
            np.asarray(X_train_scaled[idx], dtype=np.float32),
            y_train_arr[idx],
        )

    print(f"ElasticNet epoch {epoch + 1}/{ELASTIC_EPOCHS} 완료")

elastic_pred = base_elastic_model.predict(X_valid_scaled).astype(np.float32)


# XGBoost — 기존 Optuna 1차 탐색 최적값
XGB_BEST_PARAMS = {
    "n_estimators": 2000,
    "learning_rate": 0.016837,
    "max_depth": 3,
    "subsample": 0.684226,
    "colsample_bytree": 0.916064,
    "reg_alpha": 0.271880,
    "reg_lambda": 6.848673,
    "min_child_weight": 7,
    "objective": "reg:squarederror",
    "eval_metric": "rmse",
    "random_state": SEED,
    "tree_method": "hist",
    "device": XGB_DEVICE,
    "n_jobs": -1,
    "early_stopping_rounds": 100,
}


def fit_xgb_with_fallback(params, X_fit, y_fit, X_eval, y_eval):
    model = xgb.XGBRegressor(**params)

    try:
        model.fit(
            X_fit,
            y_fit,
            eval_set=[(X_eval, y_eval)],
            verbose=100,
        )
        return model

    except Exception as error:
        if params.get("device") != "cuda":
            raise

        print("CUDA 학습 실패 — CPU로 다시 실행합니다.")
        print("원래 오류:", error)

        cpu_params = params.copy()
        cpu_params["device"] = "cpu"

        model = xgb.XGBRegressor(**cpu_params)
        model.fit(
            X_fit,
            y_fit,
            eval_set=[(X_eval, y_eval)],
            verbose=100,
        )
        return model


base_xgb_model = fit_xgb_with_fallback(
    XGB_BEST_PARAMS,
    X_train,
    y_train_arr,
    X_valid,
    y_valid_arr,
)

xgb_pred = base_xgb_model.predict(X_valid).astype(np.float32)

ridge_result = evaluate_prediction("ridge", ridge_pred)
elastic_result = evaluate_prediction("elasticnet", elastic_pred)
xgb_result = evaluate_prediction("xgboost", xgb_pred)

base_results = pd.DataFrame([
    ridge_result,
    elastic_result,
    xgb_result,
]).sort_values("sharpe", ascending=False).reset_index(drop=True)

display(base_results)

joblib.dump(base_ridge_model, MODEL_DIR / "base_ridge_model.joblib")
joblib.dump(base_elastic_model, MODEL_DIR / "base_elasticnet_model.joblib")
joblib.dump(base_xgb_model, MODEL_DIR / "base_xgboost_model.joblib")
base_xgb_model.save_model(MODEL_DIR / "base_xgboost_model.json")

# 기존 CSV 형태 유지
pd.DataFrame({
    "era": val_era_arr,
    "prediction": ridge_pred,
}).to_csv(
    MODEL_DIR / "ridge_val_prediction.csv",
    index=False,
    encoding="utf-8-sig",
)

pd.DataFrame({
    "era": val_era_arr,
    "prediction": elastic_pred,
}).to_csv(
    MODEL_DIR / "elasticnet_val_prediction.csv",
    index=False,
    encoding="utf-8-sig",
)

pd.DataFrame({
    "era": val_era_arr,
    "prediction": xgb_pred,
}).to_csv(
    MODEL_DIR / "xgboost_val_prediction.csv",
    index=False,
    encoding="utf-8-sig",
)

# id와 target이 포함된 안전한 버전
for name, prediction in [
    ("ridge", ridge_pred),
    ("elasticnet", elastic_pred),
    ("xgboost", xgb_pred),
]:
    pd.DataFrame({
        "id": val_id_arr,
        "era": val_era_arr,
        "target": y_valid_arr,
        "prediction": prediction,
    }).to_csv(
        MODEL_DIR / f"{name}_realtarget_val_predictions.csv",
        index=False,
    )

ElasticNet epoch 1/20 완료
ElasticNet epoch 2/20 완료
ElasticNet epoch 3/20 완료
ElasticNet epoch 4/20 완료
ElasticNet epoch 5/20 완료
ElasticNet epoch 6/20 완료
ElasticNet epoch 7/20 완료
ElasticNet epoch 8/20 완료
ElasticNet epoch 9/20 완료
ElasticNet epoch 10/20 완료
ElasticNet epoch 11/20 완료
ElasticNet epoch 12/20 완료
ElasticNet epoch 13/20 완료
ElasticNet epoch 14/20 완료
ElasticNet epoch 15/20 완료
ElasticNet epoch 16/20 완료
ElasticNet epoch 17/20 완료
ElasticNet epoch 18/20 완료
ElasticNet epoch 19/20 완료
ElasticNet epoch 20/20 완료
[0]	validation_0-rmse:0.22369
[100]	validation_0-rmse:0.22366
[200]	validation_0-rmse:0.22365
[300]	validation_0-rmse:0.22365
[400]	validation_0-rmse:0.22363
[500]	validation_0-rmse:0.22363
[600]	validation_0-rmse:0.22363
[603]	validation_0-rmse:0.22363

========== ridge Validation Result ==========
RMSE: 0.223646
MAE: 0.150844
per-era CORR mean: 0.024467
per-era CORR std:  0.011884
Sharpe:            2.058819
================================================

========== elasticnet Validation Result ==========
RMSE: 0.225329
MAE: 0.163319
per-era CORR mean: 0.026658
per-era CORR std:  0.011869
Sharpe:            2.246006
================================================

========== xgboost Validation Result ==========
RMSE: 0.223625
MAE: 0.151929
per-era CORR mean: 0.023655
per-era CORR std:  0.009544
Sharpe:            2.478508
================================================

        model      rmse       mae  mean_corr  std_corr    sharpe
0     xgboost  0.223625  0.151929   0.023655  0.009544  2.478508
1  elasticnet  0.225329  0.163319   0.026658  0.011869  2.246006
2       ridge  0.223646  0.150844   0.024467  0.011884  2.058819

In [15]:
# ============================================
# 12. Ridge(alpha=1.0) 메타모델 + OOS 평가
# 세 기본 모델의 era별 rank를 메타 feature로 사용
# ============================================
meta_df = pd.DataFrame({
    "id": val_id_arr,
    "era": val_era_arr,
    "target": y_valid_arr,
    "ridge_prediction": ridge_pred,
    "elasticnet_prediction": elastic_pred,
    "xgboost_prediction": xgb_pred,
})

for model_name in ["ridge", "elasticnet", "xgboost"]:
    meta_df[f"{model_name}_rank"] = (
        meta_df.groupby("era")[f"{model_name}_prediction"]
        .rank(method="average", pct=True)
        .astype(np.float32)
    )

META_FEATURES = [
    "ridge_rank",
    "elasticnet_rank",
    "xgboost_rank",
]

# 앞 14 eras 학습 / 4 eras purge / 마지막 5 eras 평가
meta_eras = sorted(meta_df["era"].unique())
N_TEST_ERAS = 5
PURGE_ERAS = 4

meta_test_eras = meta_eras[-N_TEST_ERAS:]
purge_eras = meta_eras[-(N_TEST_ERAS + PURGE_ERAS):-N_TEST_ERAS]
meta_fit_eras = meta_eras[:-(N_TEST_ERAS + PURGE_ERAS)]

meta_fit_df = meta_df[meta_df["era"].isin(meta_fit_eras)].copy()
meta_test_df = meta_df[meta_df["era"].isin(meta_test_eras)].copy()

meta_model_oos = Ridge(alpha=1.0, fit_intercept=True)
meta_model_oos.fit(
    meta_fit_df[META_FEATURES],
    meta_fit_df["target"],
)

meta_test_df["stack_raw"] = meta_model_oos.predict(
    meta_test_df[META_FEATURES]
).astype(np.float32)

meta_test_df["stack_prediction"] = (
    meta_test_df.groupby("era")["stack_raw"]
    .rank(method="average", pct=True)
    .astype(np.float32)
)


def summarize_test(name, column):
    corr = simple_per_era_corr(
        meta_test_df["era"].to_numpy(),
        meta_test_df["target"].to_numpy(),
        meta_test_df[column].to_numpy(),
    )

    mean_corr = corr.mean()
    std_corr = corr.std(ddof=0)

    return {
        "model": name,
        "mean_corr": mean_corr,
        "std_corr": std_corr,
        "sharpe": mean_corr / std_corr if std_corr > 0 else np.nan,
    }


oos_results = pd.DataFrame([
    summarize_test("Ridge", "ridge_rank"),
    summarize_test("ElasticNet", "elasticnet_rank"),
    summarize_test("XGBoost", "xgboost_rank"),
    summarize_test(
        "Ridge + ElasticNet + XGBoost",
        "stack_prediction",
    ),
]).sort_values("sharpe", ascending=False).reset_index(drop=True)

print("메타 학습 era:", meta_fit_eras)
print("Purge era:", purge_eras)
print("메타 평가 era:", meta_test_eras)
print("OOS meta coefficients:", meta_model_oos.coef_)

display(oos_results)

meta_test_df[[
    "id",
    "era",
    "target",
    "ridge_rank",
    "elasticnet_rank",
    "xgboost_rank",
    "stack_prediction",
]].to_csv(
    MODEL_DIR / "ridge_elastic_xgboost_oos_predictions.csv",
    index=False,
)

joblib.dump(meta_model_oos, MODEL_DIR / "meta_ridge_alpha1_oos.joblib")

메타 학습 era: [np.int32(552), np.int32(553), np.int32(554), np.int32(555), np.int32(556), np.int32(557), np.int32(558), np.int32(559), np.int32(560), np.int32(561), np.int32(562), np.int32(563), np.int32(564), np.int32(565)]
Purge era: [np.int32(566), np.int32(567), np.int32(568), np.int32(569)]
메타 평가 era: [np.int32(570), np.int32(571), np.int32(572), np.int32(573), np.int32(574)]
OOS meta coefficients: [0.00135188 0.01433213 0.01274321]

                          model  mean_corr  std_corr    sharpe
0                         Ridge   0.016567  0.005003  3.311607
1  Ridge + ElasticNet + XGBoost   0.019217  0.006163  3.118258
2                    ElasticNet   0.018825  0.006687  2.814968
3                       XGBoost   0.014675  0.005389  2.723115

['/Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/ridge_elastic_xgboost_stack_v52/meta_ridge_alpha1_oos.joblib']

In [16]:
# ============================================
# 13. 최종 메타모델 + 기본 모델 전체 내부 데이터 재학습
# ============================================
# 메타모델은 내부 validation 전체의 세 rank feature로 학습합니다.
final_meta_model = Ridge(alpha=1.0, fit_intercept=True)
final_meta_model.fit(
    meta_df[META_FEATURES],
    meta_df["target"],
)

print("Final meta coefficients:", final_meta_model.coef_)
print("Final meta intercept:", final_meta_model.intercept_)

# 내부 train/valid 원본 feature를 하나의 disk memmap으로 합칩니다.
X_FULL_RAW_PATH = MEMMAP_DIR / "X_full_raw.dat"
full_shape = (
    X_train.shape[0] + X_valid.shape[0],
    X_train.shape[1],
)

X_full = np.memmap(
    X_FULL_RAW_PATH,
    dtype="float32",
    mode="w+",
    shape=full_shape,
)
X_full[:X_train.shape[0]] = X_train
X_full[X_train.shape[0]:] = X_valid
X_full.flush()

y_full = np.concatenate([y_train_arr, y_valid_arr]).astype(np.float32)

# Ridge / ElasticNet 최종 입력 scaler
final_model_scaler = StandardScaler()

for start in range(0, X_full.shape[0], MODEL_BATCH_SIZE):
    end = min(start + MODEL_BATCH_SIZE, X_full.shape[0])
    final_model_scaler.partial_fit(X_full[start:end])
    print(f"Final model scaler: {end:,}/{X_full.shape[0]:,}")

X_FULL_SCALED_PATH = MEMMAP_DIR / "X_full_scaled.dat"
X_full_scaled = np.memmap(
    X_FULL_SCALED_PATH,
    dtype="float32",
    mode="w+",
    shape=X_full.shape,
)

for start in range(0, X_full.shape[0], MODEL_BATCH_SIZE):
    end = min(start + MODEL_BATCH_SIZE, X_full.shape[0])
    X_full_scaled[start:end] = final_model_scaler.transform(
        X_full[start:end]
    ).astype(np.float32)
    print(f"Final full scaling: {end:,}/{X_full.shape[0]:,}")

X_full_scaled.flush()

# Final Ridge
final_ridge_model = Ridge(
    alpha=BASE_RIDGE_ALPHA,
    fit_intercept=True,
    solver="lsqr",
    max_iter=5000,
    tol=1e-4,
)
final_ridge_model.fit(X_full_scaled, y_full)

# Final ElasticNet
final_elastic_model = SGDRegressor(
    loss="squared_error",
    penalty="elasticnet",
    alpha=1e-3,
    l1_ratio=0.03,
    learning_rate="invscaling",
    eta0=0.001,
    power_t=0.5,
    max_iter=1,
    tol=None,
    random_state=SEED,
    average=True,
)

rng = np.random.default_rng(SEED)

for epoch in range(ELASTIC_EPOCHS):
    indices = rng.permutation(X_full_scaled.shape[0])

    for start in range(0, len(indices), MODEL_BATCH_SIZE):
        end = min(start + MODEL_BATCH_SIZE, len(indices))
        idx = indices[start:end]

        final_elastic_model.partial_fit(
            np.asarray(X_full_scaled[idx], dtype=np.float32),
            y_full[idx],
        )

    print(f"Final ElasticNet epoch {epoch + 1}/{ELASTIC_EPOCHS} 완료")

# Final XGBoost
# 내부 early stopping에서 선택된 트리 수를 전체 재학습에 사용합니다.
if getattr(base_xgb_model, "best_iteration", None) is not None:
    FINAL_XGB_ESTIMATORS = int(base_xgb_model.best_iteration) + 1
else:
    FINAL_XGB_ESTIMATORS = int(XGB_BEST_PARAMS["n_estimators"])

final_xgb_params = XGB_BEST_PARAMS.copy()
final_xgb_params.pop("early_stopping_rounds", None)
final_xgb_params["n_estimators"] = FINAL_XGB_ESTIMATORS

final_xgb_model = xgb.XGBRegressor(**final_xgb_params)

try:
    final_xgb_model.fit(
        X_full,
        y_full,
        verbose=100,
    )
except Exception as error:
    if final_xgb_params.get("device") != "cuda":
        raise

    print("Final XGBoost CUDA 학습 실패 — CPU로 다시 실행합니다.")
    print("원래 오류:", error)

    final_xgb_params["device"] = "cpu"
    final_xgb_model = xgb.XGBRegressor(**final_xgb_params)
    final_xgb_model.fit(
        X_full,
        y_full,
        verbose=100,
    )

print("Final XGBoost tree 수:", FINAL_XGB_ESTIMATORS)

# 최종 객체 저장
joblib.dump(
    final_model_scaler,
    MODEL_DIR / "final_model_input_scaler.joblib",
)
joblib.dump(
    final_ridge_model,
    MODEL_DIR / "final_ridge_model.joblib",
)
joblib.dump(
    final_elastic_model,
    MODEL_DIR / "final_elasticnet_model.joblib",
)
joblib.dump(
    final_xgb_model,
    MODEL_DIR / "final_xgboost_model.joblib",
)
joblib.dump(
    final_meta_model,
    MODEL_DIR / "final_meta_ridge_model.joblib",
)

final_xgb_model.save_model(
    MODEL_DIR / "final_xgboost_model.json"
)

with open(MODEL_DIR / "final_features.json", "w", encoding="utf-8") as file:
    json.dump(FEATURES, file, ensure_ascii=False, indent=2)

with open(MODEL_DIR / "xgboost_final_params.json", "w", encoding="utf-8") as file:
    json.dump(final_xgb_params, file, ensure_ascii=False, indent=2)

print("최종 모델 저장 완료:", MODEL_DIR)

Final meta coefficients: [-0.01328409  0.02733758  0.01115812]
Final meta intercept: 0.4873461
Final model scaler: 50,000/587,583
Final model scaler: 100,000/587,583
Final model scaler: 150,000/587,583
Final model scaler: 200,000/587,583
Final model scaler: 250,000/587,583
Final model scaler: 300,000/587,583
Final model scaler: 350,000/587,583
Final model scaler: 400,000/587,583
Final model scaler: 450,000/587,583
Final model scaler: 500,000/587,583
Final model scaler: 550,000/587,583
Final model scaler: 587,583/587,583
Final full scaling: 50,000/587,583
Final full scaling: 100,000/587,583
Final full scaling: 150,000/587,583
Final full scaling: 200,000/587,583
Final full scaling: 250,000/587,583
Final full scaling: 300,000/587,583
Final full scaling: 350,000/587,583
Final full scaling: 400,000/587,583
Final full scaling: 450,000/587,583
Final full scaling: 500,000/587,583
Final full scaling: 550,000/587,583
Final full scaling: 587,583/587,583
Final ElasticNet epoch 1/20 완료
Final ElasticNet epoch 2/20 완료
Final ElasticNet epoch 3/20 완료
Final ElasticNet epoch 4/20 완료
Final ElasticNet epoch 5/20 완료
Final ElasticNet epoch 6/20 완료
Final ElasticNet epoch 7/20 완료
Final ElasticNet epoch 8/20 완료
Final ElasticNet epoch 9/20 완료
Final ElasticNet epoch 10/20 완료
Final ElasticNet epoch 11/20 완료
Final ElasticNet epoch 12/20 완료
Final ElasticNet epoch 13/20 완료
Final ElasticNet epoch 14/20 완료
Final ElasticNet epoch 15/20 완료
Final ElasticNet epoch 16/20 완료
Final ElasticNet epoch 17/20 완료
Final ElasticNet epoch 18/20 완료
Final ElasticNet epoch 19/20 완료
Final ElasticNet epoch 20/20 완료
Final XGBoost tree 수: 504
최종 모델 저장 완료: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/ridge_elastic_xgboost_stack_v52

In [17]:
# ============================================
# 14. 공식 validation.parquet → PCA500
# ============================================
if not VALIDATION_PCA_ALL_PATH.exists():
    transform_source_to_pca(
        VALIDATION_PATH,
        VALIDATION_PCA_ALL_PATH,
        filter_validation=True,
    )
else:
    print("기존 파일 사용:", VALIDATION_PCA_ALL_PATH)

기존 파일 사용: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/cache_v52/validation_pca_all.parquet

In [18]:
# ============================================
# 15. 공식 validation PCA500 → lag1/lag2 → 1500 features
# ============================================
validation_era_mean_df = compute_era_means(VALIDATION_PCA_ALL_PATH)
validation_eras = sorted(
    validation_era_mean_df.index.astype(int).tolist()
)
validation_era_set = set(validation_eras)

validation_lag1, validation_lag2 = make_lag_lookup(
    validation_era_mean_df,
    validation_era_set,
)

remove_if_exists(VALIDATION_FINAL_PATH)
validation_writer = {
    "path": VALIDATION_FINAL_PATH,
    "object": None,
}
validation_rows = 0

try:
    for chunk in iter_parquet_batches(
        VALIDATION_PCA_ALL_PATH,
        ["id", "era", TARGET_COL] + pca_cols,
        TRANSFORM_BATCH_SIZE,
    ):
        era_array = chunk["era"].to_numpy(dtype=np.int32)

        lag1_array = np.vstack([
            validation_lag1[int(era)]
            for era in era_array
        ])
        lag2_array = np.vstack([
            validation_lag2[int(era)]
            for era in era_array
        ])

        final = pd.concat(
            [
                chunk[["id"] + pca_cols].reset_index(drop=True),
                pd.DataFrame(lag1_array, columns=lag1_cols),
                pd.DataFrame(lag2_array, columns=lag2_cols),
            ],
            axis=1,
        )

        final["era"] = era_array
        final[TARGET_COL] = chunk[TARGET_COL].to_numpy(dtype=np.float32)
        final = final[["id"] + FEATURES + ["era", TARGET_COL]]

        append_parquet_batch(validation_writer, final)
        validation_rows += len(final)
        print(f"validation final: {validation_rows:,} rows")

finally:
    close_writer(validation_writer)

print("공식 validation 전처리 저장:", VALIDATION_FINAL_PATH)
print("era:", min(validation_eras), "~", max(validation_eras))

validation final: 20,000 rows
validation final: 40,000 rows
validation final: 60,000 rows
validation final: 80,000 rows
validation final: 100,000 rows
validation final: 120,000 rows
validation final: 140,000 rows
validation final: 160,000 rows
validation final: 180,000 rows
validation final: 200,000 rows
validation final: 220,000 rows
validation final: 240,000 rows
validation final: 260,000 rows
validation final: 280,000 rows
validation final: 300,000 rows
validation final: 320,000 rows
validation final: 340,000 rows
validation final: 360,000 rows
validation final: 380,000 rows
validation final: 400,000 rows
validation final: 420,000 rows
validation final: 440,000 rows
validation final: 460,000 rows
validation final: 480,000 rows
validation final: 500,000 rows
validation final: 520,000 rows
validation final: 540,000 rows
validation final: 560,000 rows
validation final: 580,000 rows
validation final: 600,000 rows
validation final: 620,000 rows
validation final: 640,000 rows
validation final: 660,000 rows
validation final: 680,000 rows
validation final: 700,000 rows
validation final: 720,000 rows
validation final: 740,000 rows
validation final: 760,000 rows
validation final: 780,000 rows
validation final: 800,000 rows
validation final: 820,000 rows
validation final: 840,000 rows
validation final: 860,000 rows
validation final: 880,000 rows
validation final: 900,000 rows
validation final: 920,000 rows
validation final: 940,000 rows
validation final: 960,000 rows
validation final: 980,000 rows
validation final: 1,000,000 rows
validation final: 1,020,000 rows
validation final: 1,040,000 rows
validation final: 1,060,000 rows
validation final: 1,080,000 rows
validation final: 1,100,000 rows
validation final: 1,120,000 rows
validation final: 1,140,000 rows
validation final: 1,160,000 rows
validation final: 1,180,000 rows
validation final: 1,200,000 rows
validation final: 1,220,000 rows
validation final: 1,240,000 rows
validation final: 1,260,000 rows
validation final: 1,280,000 rows
validation final: 1,300,000 rows
validation final: 1,320,000 rows
validation final: 1,340,000 rows
validation final: 1,360,000 rows
validation final: 1,380,000 rows
validation final: 1,400,000 rows
validation final: 1,420,000 rows
validation final: 1,440,000 rows
validation final: 1,460,000 rows
validation final: 1,480,000 rows
validation final: 1,500,000 rows
validation final: 1,520,000 rows
validation final: 1,540,000 rows
validation final: 1,560,000 rows
validation final: 1,580,000 rows
validation final: 1,600,000 rows
validation final: 1,620,000 rows
validation final: 1,640,000 rows
validation final: 1,660,000 rows
validation final: 1,680,000 rows
validation final: 1,700,000 rows
validation final: 1,720,000 rows
validation final: 1,740,000 rows
validation final: 1,760,000 rows
validation final: 1,780,000 rows
validation final: 1,800,000 rows
validation final: 1,820,000 rows
validation final: 1,840,000 rows
validation final: 1,860,000 rows
validation final: 1,880,000 rows
validation final: 1,900,000 rows
validation final: 1,920,000 rows
validation final: 1,940,000 rows
validation final: 1,960,000 rows
validation final: 1,980,000 rows
validation final: 2,000,000 rows
validation final: 2,020,000 rows
validation final: 2,040,000 rows
validation final: 2,060,000 rows
validation final: 2,080,000 rows
validation final: 2,100,000 rows
validation final: 2,120,000 rows
validation final: 2,140,000 rows
validation final: 2,160,000 rows
validation final: 2,180,000 rows
validation final: 2,200,000 rows
validation final: 2,220,000 rows
validation final: 2,240,000 rows
validation final: 2,260,000 rows
validation final: 2,280,000 rows
validation final: 2,300,000 rows
validation final: 2,320,000 rows
validation final: 2,340,000 rows
validation final: 2,360,000 rows
validation final: 2,380,000 rows
validation final: 2,400,000 rows
validation final: 2,420,000 rows
validation final: 2,440,000 rows
validation final: 2,460,000 rows
validation final: 2,480,000 rows
validation final: 2,500,000 rows
validation final: 2,520,000 rows
validation final: 2,540,000 rows
validation final: 2,560,000 rows
validation final: 2,580,000 rows
validation final: 2,600,000 rows
validation final: 2,620,000 rows
validation final: 2,640,000 rows
validation final: 2,660,000 rows
validation final: 2,680,000 rows
validation final: 2,700,000 rows
validation final: 2,720,000 rows
validation final: 2,740,000 rows
validation final: 2,760,000 rows
validation final: 2,780,000 rows
validation final: 2,800,000 rows
validation final: 2,820,000 rows
validation final: 2,840,000 rows
validation final: 2,860,000 rows
validation final: 2,880,000 rows
validation final: 2,900,000 rows
validation final: 2,920,000 rows
validation final: 2,940,000 rows
validation final: 2,960,000 rows
validation final: 2,980,000 rows
validation final: 3,000,000 rows
validation final: 3,020,000 rows
validation final: 3,040,000 rows
validation final: 3,060,000 rows
validation final: 3,080,000 rows
validation final: 3,100,000 rows
validation final: 3,120,000 rows
validation final: 3,140,000 rows
validation final: 3,160,000 rows
validation final: 3,180,000 rows
validation final: 3,200,000 rows
validation final: 3,220,000 rows
validation final: 3,240,000 rows
validation final: 3,260,000 rows
validation final: 3,280,000 rows
validation final: 3,300,000 rows
validation final: 3,320,000 rows
validation final: 3,340,000 rows
validation final: 3,360,000 rows
validation final: 3,380,000 rows
validation final: 3,400,000 rows
validation final: 3,420,000 rows
validation final: 3,440,000 rows
validation final: 3,460,000 rows
validation final: 3,480,000 rows
validation final: 3,500,000 rows
validation final: 3,520,000 rows
validation final: 3,540,000 rows
validation final: 3,560,000 rows
validation final: 3,580,000 rows
validation final: 3,600,000 rows
validation final: 3,620,000 rows
validation final: 3,640,000 rows
validation final: 3,660,000 rows
validation final: 3,680,000 rows
validation final: 3,700,000 rows
validation final: 3,720,000 rows
validation final: 3,740,000 rows
validation final: 3,760,000 rows
validation final: 3,780,000 rows
validation final: 3,800,000 rows
validation final: 3,820,000 rows
validation final: 3,840,000 rows
validation final: 3,860,000 rows
validation final: 3,880,000 rows
validation final: 3,900,000 rows
validation final: 3,920,000 rows
validation final: 3,940,000 rows
validation final: 3,960,000 rows
validation final: 3,980,000 rows
validation final: 4,000,000 rows
validation final: 4,020,000 rows
validation final: 4,040,000 rows
validation final: 4,050,241 rows
공식 validation 전처리 저장: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/cache_v52/validation_pca500_lag1_lag2.parquet
era: 575 ~ 1223

In [19]:
# ============================================
# 16. 공식 validation 예측 + Diagnostics CSV + 로컬 CORR
# era가 끝날 때마다 저장하여 메모리를 절약합니다.
# ============================================
DIAGNOSTICS_CSV = (
    DIAGNOSTICS_DIR
    / "ridge_elastic_xgboost_v52_diagnostics.csv"
)
PER_ERA_CSV = (
    DIAGNOSTICS_DIR
    / "ridge_elastic_xgboost_v52_per_era_corr.csv"
)
SUMMARY_CSV = (
    DIAGNOSTICS_DIR
    / "ridge_elastic_xgboost_v52_local_summary.csv"
)

remove_if_exists(DIAGNOSTICS_CSV)

state = {
    "era": None,
    "id": [],
    "target": [],
    "ridge": [],
    "elastic": [],
    "xgboost": [],
}

per_era_rows = []
header_written = False
last_seen_era = None


def flush_era_state():
    global header_written

    if state["era"] is None:
        return

    era_df = pd.DataFrame({
        "id": np.concatenate(state["id"]),
        "target": np.concatenate(state["target"]),
        "ridge_prediction": np.concatenate(state["ridge"]),
        "elasticnet_prediction": np.concatenate(state["elastic"]),
        "xgboost_prediction": np.concatenate(state["xgboost"]),
    })

    for model_name in ["ridge", "elasticnet", "xgboost"]:
        source_column = (
            "elasticnet_prediction"
            if model_name == "elasticnet"
            else f"{model_name}_prediction"
        )
        era_df[f"{model_name}_rank"] = (
            era_df[source_column]
            .rank(method="average", pct=True)
            .astype(np.float32)
        )

    meta_X = era_df[META_FEATURES].to_numpy(dtype=np.float32)
    era_df["stack_raw"] = final_meta_model.predict(meta_X).astype(np.float32)
    era_df["prediction"] = (
        era_df["stack_raw"]
        .rank(method="average", pct=True)
        .astype(np.float32)
    )

    score_data = era_df[["prediction", "target"]].dropna()
    score = numerai_corr(
        score_data[["prediction"]],
        score_data["target"],
    )
    score_value = float(np.asarray(score).reshape(-1)[0])

    era_df[["id", "prediction"]].to_csv(
        DIAGNOSTICS_CSV,
        mode="a",
        header=not header_written,
        index=False,
    )
    header_written = True

    per_era_rows.append({
        "era": int(state["era"]),
        "corr": score_value,
        "rows": len(era_df),
    })

    print(
        f"era {state['era']} 저장 | "
        f"rows={len(era_df):,} | CORR={score_value:.6f}"
    )

    state["era"] = None
    state["id"] = []
    state["target"] = []
    state["ridge"] = []
    state["elastic"] = []
    state["xgboost"] = []


for chunk in iter_parquet_batches(
    VALIDATION_FINAL_PATH,
    ["id", "era", TARGET_COL] + FEATURES,
    TRANSFORM_BATCH_SIZE,
):
    chunk = chunk.reset_index(drop=True)

    X_model = clean_array(
        chunk[FEATURES].to_numpy(dtype=np.float32)
    )
    X_scaled = final_model_scaler.transform(X_model).astype(np.float32)

    ridge_chunk = final_ridge_model.predict(X_scaled).astype(np.float32)
    elastic_chunk = final_elastic_model.predict(X_scaled).astype(np.float32)
    xgboost_chunk = final_xgb_model.predict(X_model).astype(np.float32)

    for era, positions in chunk.groupby("era", sort=False).groups.items():
        era = int(era)
        positions = np.asarray(list(positions), dtype=int)

        if last_seen_era is not None and era < last_seen_era:
            raise ValueError(
                "validation parquet이 era 순서가 아닙니다. "
                "먼저 era 기준 정렬 파일을 만들어야 합니다."
            )

        last_seen_era = era

        if state["era"] is not None and era != state["era"]:
            flush_era_state()

        if state["era"] is None:
            state["era"] = era

        state["id"].append(
            chunk.iloc[positions]["id"].astype(str).to_numpy()
        )
        state["target"].append(
            chunk.iloc[positions][TARGET_COL].to_numpy(dtype=np.float32)
        )
        state["ridge"].append(ridge_chunk[positions])
        state["elastic"].append(elastic_chunk[positions])
        state["xgboost"].append(xgboost_chunk[positions])

flush_era_state()

per_era_df = pd.DataFrame(per_era_rows).sort_values("era")
per_era_df.to_csv(PER_ERA_CSV, index=False)

corr_mean = per_era_df["corr"].mean()
corr_std = per_era_df["corr"].std(ddof=0)
corr_sharpe = corr_mean / corr_std if corr_std > 0 else np.nan

cumulative = per_era_df["corr"].cumsum()
max_drawdown = (
    cumulative.expanding(min_periods=1).max() - cumulative
).max()

summary_df = pd.DataFrame({
    "metric": [
        "mean_corr",
        "std_corr",
        "sharpe",
        "max_drawdown",
        "eras",
    ],
    "value": [
        corr_mean,
        corr_std,
        corr_sharpe,
        max_drawdown,
        len(per_era_df),
    ],
})
summary_df.to_csv(SUMMARY_CSV, index=False)

display(summary_df)
print("Diagnostics CSV:", DIAGNOSTICS_CSV)

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 575 저장 | rows=5,592 | CORR=0.020510
era 576 저장 | rows=5,638 | CORR=0.010800
era 577 저장 | rows=5,675 | CORR=0.009182
era 578 저장 | rows=5,786 | CORR=0.014243

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 579 저장 | rows=5,868 | CORR=0.016020
era 580 저장 | rows=5,875 | CORR=0.013124
era 581 저장 | rows=5,840 | CORR=0.010940
era 582 저장 | rows=5,819 | CORR=0.017319
era 583 저장 | rows=5,814 | CORR=0.030153

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 584 저장 | rows=5,840 | CORR=0.027861
era 585 저장 | rows=5,848 | CORR=0.032576
era 586 저장 | rows=5,928 | CORR=0.032117
era 587 저장 | rows=5,945 | CORR=0.022375
era 588 저장 | rows=5,959 | CORR=0.015322
era 589 저장 | rows=5,949 | CORR=0.004269
era 590 저장 | rows=5,893 | CORR=0.005080
era 591 저장 | rows=5,794 | CORR=0.010082

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 592 저장 | rows=5,696 | CORR=0.011293
era 593 저장 | rows=5,633 | CORR=0.016546
era 594 저장 | rows=5,665 | CORR=0.009771
era 595 저장 | rows=5,697 | CORR=0.002641
era 596 저장 | rows=5,710 | CORR=0.020961

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 597 저장 | rows=5,753 | CORR=0.024594
era 598 저장 | rows=5,775 | CORR=0.023293
era 599 저장 | rows=5,832 | CORR=0.022002
era 600 저장 | rows=5,855 | CORR=0.023190
era 601 저장 | rows=5,834 | CORR=0.018430

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 602 저장 | rows=5,829 | CORR=0.020739
era 603 저장 | rows=5,749 | CORR=0.006518
era 604 저장 | rows=5,727 | CORR=0.001995
era 605 저장 | rows=5,717 | CORR=0.000505
era 606 저장 | rows=5,706 | CORR=0.009864

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 607 저장 | rows=5,698 | CORR=-0.000422
era 608 저장 | rows=5,706 | CORR=0.010629
era 609 저장 | rows=5,666 | CORR=0.020269
era 610 저장 | rows=5,664 | CORR=0.028503
era 611 저장 | rows=5,682 | CORR=0.027011

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 612 저장 | rows=5,739 | CORR=0.022963
era 613 저장 | rows=5,888 | CORR=0.034304
era 614 저장 | rows=5,896 | CORR=0.034258
era 615 저장 | rows=5,901 | CORR=0.004580

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 616 저장 | rows=5,966 | CORR=-0.000741
era 617 저장 | rows=5,952 | CORR=0.015047
era 618 저장 | rows=5,957 | CORR=0.018476
era 619 저장 | rows=5,967 | CORR=0.032289

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 620 저장 | rows=5,888 | CORR=0.020154
era 621 저장 | rows=5,899 | CORR=-0.008128
era 622 저장 | rows=5,869 | CORR=-0.012661
era 623 저장 | rows=5,865 | CORR=-0.003516

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 624 저장 | rows=5,868 | CORR=-0.001876
era 625 저장 | rows=5,950 | CORR=0.003878
era 626 저장 | rows=5,884 | CORR=0.012201
era 627 저장 | rows=5,504 | CORR=0.019355
era 628 저장 | rows=5,522 | CORR=0.012841

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 629 저장 | rows=5,450 | CORR=0.017193
era 630 저장 | rows=5,579 | CORR=0.018287
era 631 저장 | rows=5,678 | CORR=0.024651
era 632 저장 | rows=5,691 | CORR=0.043693

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 633 저장 | rows=5,674 | CORR=0.039751
era 634 저장 | rows=5,657 | CORR=0.032150
era 635 저장 | rows=5,725 | CORR=0.031949
era 636 저장 | rows=5,737 | CORR=0.029058
era 637 저장 | rows=5,798 | CORR=0.031729

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 638 저장 | rows=5,870 | CORR=0.045499
era 639 저장 | rows=5,903 | CORR=0.035527
era 640 저장 | rows=5,846 | CORR=0.024906
era 641 저장 | rows=6,000 | CORR=0.033817

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 642 저장 | rows=6,034 | CORR=0.013552
era 643 저장 | rows=6,022 | CORR=0.014143
era 644 저장 | rows=6,076 | CORR=0.013152
era 645 저장 | rows=6,065 | CORR=0.018898

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 646 저장 | rows=6,041 | CORR=0.021014
era 647 저장 | rows=6,061 | CORR=0.020372
era 648 저장 | rows=6,016 | CORR=0.030047
era 649 저장 | rows=6,017 | CORR=0.019607

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 650 저장 | rows=5,986 | CORR=0.009080
era 651 저장 | rows=6,020 | CORR=0.023036
era 652 저장 | rows=5,983 | CORR=0.016066
era 653 저장 | rows=5,968 | CORR=0.030499
era 654 저장 | rows=6,037 | CORR=0.020991

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 655 저장 | rows=5,954 | CORR=0.023025
era 656 저장 | rows=5,901 | CORR=0.015897
era 657 저장 | rows=5,825 | CORR=0.008827
era 658 저장 | rows=5,756 | CORR=0.012089
era 659 저장 | rows=5,712 | CORR=0.012443

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 660 저장 | rows=5,722 | CORR=0.018912
era 661 저장 | rows=5,803 | CORR=0.015388
era 662 저장 | rows=5,836 | CORR=0.003914
era 663 저장 | rows=5,809 | CORR=0.017096
era 664 저장 | rows=5,783 | CORR=0.009555

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 665 저장 | rows=5,727 | CORR=0.038492
era 666 저장 | rows=5,705 | CORR=0.011659
era 667 저장 | rows=5,744 | CORR=0.017315
era 668 저장 | rows=5,760 | CORR=0.022898
era 669 저장 | rows=5,750 | CORR=0.026011

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 670 저장 | rows=5,709 | CORR=0.020814
era 671 저장 | rows=5,707 | CORR=0.003723
era 672 저장 | rows=5,691 | CORR=0.002561
era 673 저장 | rows=5,713 | CORR=0.011967

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 674 저장 | rows=5,669 | CORR=0.016772
era 675 저장 | rows=5,701 | CORR=0.000888
era 676 저장 | rows=5,663 | CORR=0.006573
era 677 저장 | rows=5,662 | CORR=0.005320
era 678 저장 | rows=5,589 | CORR=0.017209

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 679 저장 | rows=5,683 | CORR=0.024019
era 680 저장 | rows=5,585 | CORR=0.005992
era 681 저장 | rows=5,550 | CORR=0.000715

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 682 저장 | rows=5,677 | CORR=0.000990
era 683 저장 | rows=5,735 | CORR=0.023242
era 684 저장 | rows=5,705 | CORR=0.024604
era 685 저장 | rows=5,627 | CORR=0.028710

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 686 저장 | rows=5,624 | CORR=0.026539
era 687 저장 | rows=5,612 | CORR=0.011447
era 688 저장 | rows=5,675 | CORR=0.023914
era 689 저장 | rows=5,684 | CORR=0.038221

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 690 저장 | rows=5,770 | CORR=0.016841
era 691 저장 | rows=5,850 | CORR=0.022491
era 692 저장 | rows=5,753 | CORR=0.020158
era 693 저장 | rows=5,694 | CORR=0.019634

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 694 저장 | rows=5,675 | CORR=0.009364
era 695 저장 | rows=5,699 | CORR=0.011106
era 696 저장 | rows=5,681 | CORR=-0.002991

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 697 저장 | rows=5,649 | CORR=0.016807
era 698 저장 | rows=5,642 | CORR=-0.006484

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 699 저장 | rows=5,624 | CORR=-0.000487
era 700 저장 | rows=5,594 | CORR=-0.002916
era 701 저장 | rows=5,610 | CORR=-0.005627
era 702 저장 | rows=5,585 | CORR=0.030431

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 703 저장 | rows=5,641 | CORR=0.008413
era 704 저장 | rows=5,656 | CORR=0.016595
era 705 저장 | rows=5,760 | CORR=0.019985
era 706 저장 | rows=5,734 | CORR=0.027449

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 707 저장 | rows=5,757 | CORR=0.022978
era 708 저장 | rows=5,708 | CORR=0.008650
era 709 저장 | rows=5,681 | CORR=0.004289
era 710 저장 | rows=5,722 | CORR=0.018151

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 711 저장 | rows=5,709 | CORR=0.012081
era 712 저장 | rows=5,685 | CORR=0.007827
era 713 저장 | rows=5,686 | CORR=0.016969

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 714 저장 | rows=5,683 | CORR=-0.005230
era 715 저장 | rows=5,650 | CORR=0.008729
era 716 저장 | rows=5,684 | CORR=0.024898

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 717 저장 | rows=5,779 | CORR=0.023672
era 718 저장 | rows=5,760 | CORR=0.031858
era 719 저장 | rows=5,740 | CORR=0.034838

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 720 저장 | rows=5,688 | CORR=0.040833
era 721 저장 | rows=5,649 | CORR=0.039952
era 722 저장 | rows=5,618 | CORR=0.027580
era 723 저장 | rows=5,631 | CORR=0.029119

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 724 저장 | rows=5,703 | CORR=0.026961
era 725 저장 | rows=5,798 | CORR=0.013882
era 726 저장 | rows=5,815 | CORR=0.001491

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 727 저장 | rows=5,830 | CORR=0.015640
era 728 저장 | rows=5,793 | CORR=0.011510
era 729 저장 | rows=5,842 | CORR=0.015979

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 730 저장 | rows=5,837 | CORR=0.026887
era 731 저장 | rows=5,699 | CORR=0.034266
era 732 저장 | rows=5,634 | CORR=0.013545
era 733 저장 | rows=5,594 | CORR=0.019375

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 734 저장 | rows=5,616 | CORR=0.019844
era 735 저장 | rows=5,694 | CORR=0.029616
era 736 저장 | rows=5,713 | CORR=0.027833
era 737 저장 | rows=5,742 | CORR=0.041096
era 738 저장 | rows=5,817 | CORR=0.038067

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 739 저장 | rows=5,891 | CORR=0.035809
era 740 저장 | rows=5,938 | CORR=0.036705
era 741 저장 | rows=5,948 | CORR=0.025678
era 742 저장 | rows=5,967 | CORR=0.045755
era 743 저장 | rows=5,982 | CORR=0.032415

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 744 저장 | rows=5,945 | CORR=0.028080
era 745 저장 | rows=5,971 | CORR=0.025711
era 746 저장 | rows=6,012 | CORR=0.023469
era 747 저장 | rows=5,896 | CORR=0.027404

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 748 저장 | rows=5,901 | CORR=0.011303
era 749 저장 | rows=5,871 | CORR=0.017788
era 750 저장 | rows=5,949 | CORR=0.018267
era 751 저장 | rows=6,029 | CORR=0.020772

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 752 저장 | rows=6,009 | CORR=0.013245
era 753 저장 | rows=6,038 | CORR=0.004648
era 754 저장 | rows=6,022 | CORR=0.023419
era 755 저장 | rows=6,016 | CORR=0.038935

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 756 저장 | rows=6,030 | CORR=0.033805
era 757 저장 | rows=6,066 | CORR=0.027263
era 758 저장 | rows=5,975 | CORR=0.020886
era 759 저장 | rows=5,922 | CORR=0.020077

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 760 저장 | rows=5,949 | CORR=0.012725
era 761 저장 | rows=5,972 | CORR=0.017868
era 762 저장 | rows=6,008 | CORR=0.025187
era 763 저장 | rows=6,049 | CORR=0.003624

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 764 저장 | rows=6,040 | CORR=0.021180
era 765 저장 | rows=6,037 | CORR=0.032323
era 766 저장 | rows=5,917 | CORR=0.038893
era 767 저장 | rows=6,039 | CORR=0.018921

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 768 저장 | rows=6,102 | CORR=0.028772
era 769 저장 | rows=6,261 | CORR=0.036420
era 770 저장 | rows=6,302 | CORR=0.011571

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 771 저장 | rows=6,297 | CORR=0.023439
era 772 저장 | rows=6,265 | CORR=0.006510
era 773 저장 | rows=6,202 | CORR=0.002460
era 774 저장 | rows=6,215 | CORR=0.013693

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 775 저장 | rows=6,302 | CORR=-0.003014
era 776 저장 | rows=6,352 | CORR=0.010628
era 777 저장 | rows=6,391 | CORR=0.001014

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 778 저장 | rows=6,407 | CORR=0.003345
era 779 저장 | rows=6,413 | CORR=0.000977
era 780 저장 | rows=6,367 | CORR=0.007866

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 781 저장 | rows=6,379 | CORR=-0.001489
era 782 저장 | rows=6,364 | CORR=0.009653
era 783 저장 | rows=6,228 | CORR=0.006003

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 784 저장 | rows=6,212 | CORR=0.021785
era 785 저장 | rows=6,210 | CORR=-0.002782
era 786 저장 | rows=6,306 | CORR=-0.004389

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 787 저장 | rows=6,416 | CORR=0.005553
era 788 저장 | rows=6,501 | CORR=0.000340
era 789 저장 | rows=6,552 | CORR=0.015833

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 790 저장 | rows=6,567 | CORR=0.030256
era 791 저장 | rows=6,514 | CORR=0.028972
era 792 저장 | rows=6,470 | CORR=0.012211

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 793 저장 | rows=6,346 | CORR=0.000410
era 794 저장 | rows=6,413 | CORR=0.020204
era 795 저장 | rows=6,431 | CORR=0.008418

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 796 저장 | rows=6,376 | CORR=0.007959
era 797 저장 | rows=6,395 | CORR=0.005922
era 798 저장 | rows=6,355 | CORR=0.009141

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 799 저장 | rows=6,334 | CORR=0.017413
era 800 저장 | rows=6,254 | CORR=0.019034
era 801 저장 | rows=6,242 | CORR=0.041929

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 802 저장 | rows=6,246 | CORR=0.019872
era 803 저장 | rows=6,266 | CORR=0.020230
era 804 저장 | rows=6,283 | CORR=0.016794
era 805 저장 | rows=6,343 | CORR=0.009965

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 806 저장 | rows=6,336 | CORR=0.001448
era 807 저장 | rows=6,309 | CORR=-0.005213
era 808 저장 | rows=6,354 | CORR=0.003506

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 809 저장 | rows=6,398 | CORR=-0.007275
era 810 저장 | rows=6,348 | CORR=-0.008160
era 811 저장 | rows=6,270 | CORR=-0.016057

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 812 저장 | rows=6,132 | CORR=-0.000160
era 813 저장 | rows=6,051 | CORR=0.008030
era 814 저장 | rows=6,089 | CORR=0.018758

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 815 저장 | rows=6,087 | CORR=-0.001424
era 816 저장 | rows=6,107 | CORR=-0.018881
era 817 저장 | rows=6,096 | CORR=0.010134
era 818 저장 | rows=6,046 | CORR=-0.000442

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 819 저장 | rows=6,058 | CORR=-0.009300
era 820 저장 | rows=6,024 | CORR=0.000867
era 821 저장 | rows=6,089 | CORR=-0.011237

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 822 저장 | rows=6,141 | CORR=-0.008172
era 823 저장 | rows=6,129 | CORR=0.004280
era 824 저장 | rows=6,191 | CORR=0.015959
era 825 저장 | rows=6,144 | CORR=-0.001529
era 826 저장 | rows=6,095 | CORR=-0.001338

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 827 저장 | rows=6,142 | CORR=-0.004827
era 828 저장 | rows=6,061 | CORR=-0.006048
era 829 저장 | rows=6,035 | CORR=-0.000590

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 830 저장 | rows=5,943 | CORR=-0.002588
era 831 저장 | rows=5,885 | CORR=-0.011992
era 832 저장 | rows=5,944 | CORR=-0.004291
era 833 저장 | rows=5,915 | CORR=0.011315

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 834 저장 | rows=5,949 | CORR=0.017176
era 835 저장 | rows=5,905 | CORR=0.029833
era 836 저장 | rows=5,838 | CORR=0.037212
era 837 저장 | rows=5,771 | CORR=0.035027

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 838 저장 | rows=5,693 | CORR=0.025108
era 839 저장 | rows=5,765 | CORR=0.020815
era 840 저장 | rows=5,796 | CORR=0.010469
era 841 저장 | rows=5,772 | CORR=0.003146

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 842 저장 | rows=5,790 | CORR=0.003259
era 843 저장 | rows=5,843 | CORR=0.010721
era 844 저장 | rows=5,895 | CORR=0.019907
era 845 저장 | rows=5,953 | CORR=0.015048

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 846 저장 | rows=5,978 | CORR=-0.002906
era 847 저장 | rows=5,993 | CORR=-0.008763
era 848 저장 | rows=5,982 | CORR=0.003754

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 849 저장 | rows=5,990 | CORR=-0.012194
era 850 저장 | rows=5,928 | CORR=-0.006394
era 851 저장 | rows=5,880 | CORR=0.024046
era 852 저장 | rows=5,818 | CORR=0.009657

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 853 저장 | rows=5,836 | CORR=0.018335
era 854 저장 | rows=5,827 | CORR=0.005258
era 855 저장 | rows=5,848 | CORR=0.015195
era 856 저장 | rows=5,828 | CORR=0.016984

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 857 저장 | rows=5,822 | CORR=0.007068
era 858 저장 | rows=5,774 | CORR=0.000895

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 859 저장 | rows=5,799 | CORR=0.005671
era 860 저장 | rows=5,811 | CORR=0.002661
era 861 저장 | rows=5,817 | CORR=-0.011586

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 862 저장 | rows=5,874 | CORR=0.008580
era 863 저장 | rows=5,860 | CORR=-0.005446
era 864 저장 | rows=5,811 | CORR=-0.010134
era 865 저장 | rows=5,779 | CORR=-0.011563

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 866 저장 | rows=5,790 | CORR=-0.009133
era 867 저장 | rows=5,820 | CORR=-0.009078
era 868 저장 | rows=5,846 | CORR=0.007468

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 869 저장 | rows=5,797 | CORR=0.001486
era 870 저장 | rows=5,782 | CORR=0.010994
era 871 저장 | rows=5,715 | CORR=-0.004155
era 872 저장 | rows=5,743 | CORR=0.007101

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 873 저장 | rows=5,852 | CORR=0.010864
era 874 저장 | rows=6,146 | CORR=0.020173
era 875 저장 | rows=6,141 | CORR=-0.000633

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 876 저장 | rows=6,080 | CORR=-0.004676
era 877 저장 | rows=6,044 | CORR=0.008299
era 878 저장 | rows=6,016 | CORR=0.008167
era 879 저장 | rows=6,055 | CORR=0.007999

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 880 저장 | rows=6,123 | CORR=0.011030
era 881 저장 | rows=6,160 | CORR=0.018425
era 882 저장 | rows=6,175 | CORR=0.024480

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 883 저장 | rows=6,155 | CORR=0.012808
era 884 저장 | rows=6,127 | CORR=0.021067
era 885 저장 | rows=6,127 | CORR=0.012923

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 886 저장 | rows=6,200 | CORR=0.026562
era 887 저장 | rows=6,173 | CORR=0.006911
era 888 저장 | rows=6,121 | CORR=0.007597

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 889 저장 | rows=6,165 | CORR=0.000297
era 890 저장 | rows=6,131 | CORR=-0.005989
era 891 저장 | rows=6,208 | CORR=-0.013692
era 892 저장 | rows=6,271 | CORR=-0.020558

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 893 저장 | rows=6,302 | CORR=-0.015643
era 894 저장 | rows=6,302 | CORR=-0.036547
era 895 저장 | rows=6,299 | CORR=-0.003388

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 896 저장 | rows=6,325 | CORR=0.000140
era 897 저장 | rows=6,400 | CORR=0.001489
era 898 저장 | rows=6,441 | CORR=0.008504

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 899 저장 | rows=6,463 | CORR=0.004784
era 900 저장 | rows=6,524 | CORR=0.003900
era 901 저장 | rows=6,459 | CORR=0.021729

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 902 저장 | rows=6,402 | CORR=0.025780
era 903 저장 | rows=6,272 | CORR=0.009026
era 904 저장 | rows=6,136 | CORR=0.011985
era 905 저장 | rows=6,192 | CORR=0.005589

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 906 저장 | rows=6,157 | CORR=0.016525
era 907 저장 | rows=6,134 | CORR=0.023095
era 908 저장 | rows=6,205 | CORR=0.012147
era 909 저장 | rows=6,247 | CORR=0.012822

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 910 저장 | rows=6,364 | CORR=0.006635
era 911 저장 | rows=6,430 | CORR=0.010990
era 912 저장 | rows=6,488 | CORR=0.016733

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 913 저장 | rows=6,279 | CORR=0.020219
era 914 저장 | rows=6,409 | CORR=0.008271
era 915 저장 | rows=6,332 | CORR=0.021254

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 916 저장 | rows=6,316 | CORR=0.005201
era 917 저장 | rows=6,301 | CORR=0.009797

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 918 저장 | rows=6,280 | CORR=0.023744
era 919 저장 | rows=6,309 | CORR=0.018596
era 920 저장 | rows=6,313 | CORR=0.036749

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 921 저장 | rows=6,298 | CORR=0.017626
era 922 저장 | rows=6,314 | CORR=-0.006140
era 923 저장 | rows=6,356 | CORR=-0.000722

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 924 저장 | rows=6,334 | CORR=0.001039
era 925 저장 | rows=6,374 | CORR=-0.011432
era 926 저장 | rows=6,548 | CORR=-0.001131
era 927 저장 | rows=6,508 | CORR=0.013639

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 928 저장 | rows=6,474 | CORR=0.014000
era 929 저장 | rows=6,400 | CORR=0.025535
era 930 저장 | rows=6,330 | CORR=0.030011

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 931 저장 | rows=6,316 | CORR=0.022096
era 932 저장 | rows=6,368 | CORR=0.003499
era 933 저장 | rows=6,500 | CORR=0.009884

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 934 저장 | rows=6,610 | CORR=0.010456
era 935 저장 | rows=6,811 | CORR=0.007174

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 936 저장 | rows=6,925 | CORR=-0.005418
era 937 저장 | rows=6,913 | CORR=0.004083
era 938 저장 | rows=6,966 | CORR=0.010370

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 939 저장 | rows=6,866 | CORR=0.007145
era 940 저장 | rows=6,798 | CORR=0.009558
era 941 저장 | rows=6,842 | CORR=0.009452

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 942 저장 | rows=6,846 | CORR=0.002856
era 943 저장 | rows=6,898 | CORR=0.014187
era 944 저장 | rows=6,953 | CORR=0.008469

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 945 저장 | rows=6,961 | CORR=-0.006346
era 946 저장 | rows=6,963 | CORR=0.015822
era 947 저장 | rows=6,996 | CORR=0.014694

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 948 저장 | rows=7,033 | CORR=0.016939
era 949 저장 | rows=7,168 | CORR=0.032926
era 950 저장 | rows=7,246 | CORR=0.005538

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 951 저장 | rows=7,309 | CORR=0.009948
era 952 저장 | rows=7,246 | CORR=0.019120

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 953 저장 | rows=7,225 | CORR=0.012151
era 954 저장 | rows=7,191 | CORR=0.015205
era 955 저장 | rows=7,067 | CORR=0.023658

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 956 저장 | rows=7,033 | CORR=0.002485
era 957 저장 | rows=7,021 | CORR=0.020905
era 958 저장 | rows=7,058 | CORR=0.011547

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 959 저장 | rows=7,117 | CORR=0.024249
era 960 저장 | rows=7,119 | CORR=0.011158
era 961 저장 | rows=7,103 | CORR=0.018325

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 962 저장 | rows=7,040 | CORR=0.027776
era 963 저장 | rows=6,996 | CORR=0.015187
era 964 저장 | rows=6,988 | CORR=0.003003

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 965 저장 | rows=7,027 | CORR=0.005230
era 966 저장 | rows=7,070 | CORR=0.002915

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 967 저장 | rows=7,063 | CORR=0.006017
era 968 저장 | rows=6,998 | CORR=0.012883
era 969 저장 | rows=6,961 | CORR=0.002924

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 970 저장 | rows=6,862 | CORR=0.005258
era 971 저장 | rows=6,870 | CORR=0.025898
era 972 저장 | rows=6,835 | CORR=0.008000

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 973 저장 | rows=6,825 | CORR=0.017380
era 974 저장 | rows=6,836 | CORR=0.026540
era 975 저장 | rows=6,904 | CORR=0.012765

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 976 저장 | rows=6,922 | CORR=0.015807
era 977 저장 | rows=6,930 | CORR=0.024802
era 978 저장 | rows=7,173 | CORR=0.012103

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 979 저장 | rows=7,188 | CORR=0.013722
era 980 저장 | rows=7,167 | CORR=0.023013
era 981 저장 | rows=7,095 | CORR=0.034542

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 982 저장 | rows=6,991 | CORR=0.030156
era 983 저장 | rows=6,934 | CORR=0.014371
era 984 저장 | rows=6,941 | CORR=0.005099

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 985 저장 | rows=6,955 | CORR=0.000782
era 986 저장 | rows=7,021 | CORR=0.021642
era 987 저장 | rows=7,042 | CORR=-0.005764

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 988 저장 | rows=7,105 | CORR=0.003830
era 989 저장 | rows=7,093 | CORR=0.017411

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 990 저장 | rows=7,094 | CORR=0.024825
era 991 저장 | rows=7,016 | CORR=0.010743
era 992 저장 | rows=6,871 | CORR=0.017087

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 993 저장 | rows=6,863 | CORR=0.012522
era 994 저장 | rows=6,844 | CORR=-0.002376
era 995 저장 | rows=6,853 | CORR=0.008451

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 996 저장 | rows=6,943 | CORR=-0.000591
era 997 저장 | rows=6,916 | CORR=0.004374
era 998 저장 | rows=6,946 | CORR=-0.004833

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 999 저장 | rows=6,906 | CORR=-0.010532
era 1000 저장 | rows=6,874 | CORR=0.010616
era 1001 저장 | rows=6,878 | CORR=0.011318

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1002 저장 | rows=6,928 | CORR=0.023629
era 1003 저장 | rows=7,018 | CORR=0.016954
era 1004 저장 | rows=7,001 | CORR=0.015823

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1005 저장 | rows=6,989 | CORR=0.034133
era 1006 저장 | rows=6,911 | CORR=0.006799
era 1007 저장 | rows=6,823 | CORR=0.020308

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1008 저장 | rows=6,687 | CORR=0.009852
era 1009 저장 | rows=6,688 | CORR=0.002527
era 1010 저장 | rows=6,587 | CORR=0.011080

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1011 저장 | rows=6,582 | CORR=0.000786
era 1012 저장 | rows=6,625 | CORR=-0.014386
era 1013 저장 | rows=6,474 | CORR=-0.006372

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1014 저장 | rows=6,503 | CORR=-0.009997
era 1015 저장 | rows=6,397 | CORR=-0.005268
era 1016 저장 | rows=6,392 | CORR=0.004680

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1017 저장 | rows=6,551 | CORR=-0.005693
era 1018 저장 | rows=6,632 | CORR=0.014067
era 1019 저장 | rows=6,584 | CORR=0.001087

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1020 저장 | rows=6,452 | CORR=0.004487
era 1021 저장 | rows=6,397 | CORR=0.018314
era 1022 저장 | rows=6,335 | CORR=0.027806

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1023 저장 | rows=6,336 | CORR=0.024970
era 1024 저장 | rows=6,389 | CORR=0.017390
era 1025 저장 | rows=6,419 | CORR=0.013169

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1026 저장 | rows=6,424 | CORR=0.012624
era 1027 저장 | rows=6,418 | CORR=0.005097
era 1028 저장 | rows=6,362 | CORR=0.014040

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1029 저장 | rows=6,373 | CORR=0.013764
era 1030 저장 | rows=6,415 | CORR=0.014417
era 1031 저장 | rows=6,230 | CORR=0.019703

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1032 저장 | rows=6,204 | CORR=0.010055
era 1033 저장 | rows=6,117 | CORR=0.009570
era 1034 저장 | rows=6,062 | CORR=-0.004874
era 1035 저장 | rows=6,008 | CORR=0.002837

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1036 저장 | rows=6,030 | CORR=0.011728
era 1037 저장 | rows=6,092 | CORR=-0.000266
era 1038 저장 | rows=6,188 | CORR=0.013850

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1039 저장 | rows=6,212 | CORR=0.005484
era 1040 저장 | rows=6,297 | CORR=0.005303
era 1041 저장 | rows=6,263 | CORR=0.002131

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1042 저장 | rows=6,222 | CORR=0.007002
era 1043 저장 | rows=6,216 | CORR=0.006648
era 1044 저장 | rows=6,086 | CORR=0.012268
era 1045 저장 | rows=6,027 | CORR=0.020191

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1046 저장 | rows=6,007 | CORR=0.033299
era 1047 저장 | rows=6,029 | CORR=0.034943
era 1048 저장 | rows=6,099 | CORR=0.013923

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1049 저장 | rows=6,215 | CORR=0.019989
era 1050 저장 | rows=6,220 | CORR=0.026131
era 1051 저장 | rows=6,284 | CORR=0.002035

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1052 저장 | rows=6,318 | CORR=0.013961
era 1053 저장 | rows=6,335 | CORR=-0.006204
era 1054 저장 | rows=6,378 | CORR=0.009750

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1055 저장 | rows=6,455 | CORR=-0.003569
era 1056 저장 | rows=6,492 | CORR=-0.000803
era 1057 저장 | rows=6,442 | CORR=0.009017

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1058 저장 | rows=6,391 | CORR=-0.002110
era 1059 저장 | rows=6,304 | CORR=-0.004680
era 1060 저장 | rows=6,291 | CORR=-0.005536

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1061 저장 | rows=6,231 | CORR=0.001191
era 1062 저장 | rows=6,213 | CORR=0.015196
era 1063 저장 | rows=6,210 | CORR=0.030047
era 1064 저장 | rows=6,201 | CORR=0.009697

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1065 저장 | rows=6,209 | CORR=0.028889
era 1066 저장 | rows=6,271 | CORR=0.018406
era 1067 저장 | rows=6,280 | CORR=-0.009323

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1068 저장 | rows=6,358 | CORR=0.017832
era 1069 저장 | rows=6,356 | CORR=0.021563
era 1070 저장 | rows=6,399 | CORR=0.011017

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1071 저장 | rows=6,353 | CORR=0.010552
era 1072 저장 | rows=6,317 | CORR=-0.010382
era 1073 저장 | rows=6,263 | CORR=-0.001606

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1074 저장 | rows=6,285 | CORR=-0.004558
era 1075 저장 | rows=6,296 | CORR=-0.004064
era 1076 저장 | rows=6,272 | CORR=0.016821

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1077 저장 | rows=6,245 | CORR=0.023816
era 1078 저장 | rows=6,165 | CORR=0.024356
era 1079 저장 | rows=6,141 | CORR=0.022781
era 1080 저장 | rows=6,118 | CORR=0.008077

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1081 저장 | rows=6,147 | CORR=0.016155
era 1082 저장 | rows=6,216 | CORR=-0.011361
era 1083 저장 | rows=6,190 | CORR=0.016880

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1084 저장 | rows=6,153 | CORR=0.028240
era 1085 저장 | rows=6,096 | CORR=0.027496
era 1086 저장 | rows=6,038 | CORR=0.026413

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1087 저장 | rows=6,026 | CORR=0.018189
era 1088 저장 | rows=6,043 | CORR=0.004428
era 1089 저장 | rows=6,041 | CORR=-0.009904

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1090 저장 | rows=6,109 | CORR=0.001488
era 1091 저장 | rows=6,117 | CORR=0.002887
era 1092 저장 | rows=6,144 | CORR=-0.002953
era 1093 저장 | rows=6,210 | CORR=0.023804

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1094 저장 | rows=6,286 | CORR=0.017693
era 1095 저장 | rows=6,393 | CORR=0.012874
era 1096 저장 | rows=6,402 | CORR=0.017145

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1097 저장 | rows=6,335 | CORR=-0.002797
era 1098 저장 | rows=6,282 | CORR=-0.000168
era 1099 저장 | rows=6,229 | CORR=-0.011807

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1100 저장 | rows=6,220 | CORR=-0.006775
era 1101 저장 | rows=6,218 | CORR=0.004199
era 1102 저장 | rows=6,244 | CORR=-0.022396

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1103 저장 | rows=6,296 | CORR=-0.002567
era 1104 저장 | rows=6,303 | CORR=0.009933
era 1105 저장 | rows=6,389 | CORR=0.015212

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1106 저장 | rows=6,470 | CORR=0.021426
era 1107 저장 | rows=6,502 | CORR=0.006199
era 1108 저장 | rows=6,547 | CORR=0.010608

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1109 저장 | rows=6,531 | CORR=0.004724
era 1110 저장 | rows=6,511 | CORR=-0.002942
era 1111 저장 | rows=6,468 | CORR=0.011584
era 1112 저장 | rows=6,430 | CORR=0.014182

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1113 저장 | rows=6,378 | CORR=0.001812
era 1114 저장 | rows=6,329 | CORR=0.002567
era 1115 저장 | rows=6,328 | CORR=-0.001704

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1116 저장 | rows=6,357 | CORR=0.008465
era 1117 저장 | rows=6,382 | CORR=0.009348
era 1118 저장 | rows=6,378 | CORR=0.008130

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1119 저장 | rows=6,385 | CORR=0.020210
era 1120 저장 | rows=6,313 | CORR=0.008962
era 1121 저장 | rows=6,300 | CORR=-0.007313

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1122 저장 | rows=6,267 | CORR=-0.004048
era 1123 저장 | rows=6,315 | CORR=-0.038258
era 1124 저장 | rows=6,323 | CORR=-0.020663

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1125 저장 | rows=6,322 | CORR=0.001940
era 1126 저장 | rows=6,328 | CORR=-0.008458
era 1127 저장 | rows=6,366 | CORR=0.008785

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1128 저장 | rows=6,376 | CORR=-0.002264
era 1129 저장 | rows=6,361 | CORR=-0.003451
era 1130 저장 | rows=6,303 | CORR=-0.002420

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1131 저장 | rows=6,210 | CORR=0.013293
era 1132 저장 | rows=6,102 | CORR=0.009682
era 1133 저장 | rows=6,141 | CORR=-0.007595
era 1134 저장 | rows=6,222 | CORR=-0.007301

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1135 저장 | rows=6,360 | CORR=-0.026292
era 1136 저장 | rows=6,371 | CORR=-0.017169
era 1137 저장 | rows=6,434 | CORR=-0.015716

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1138 저장 | rows=6,385 | CORR=-0.011389
era 1139 저장 | rows=6,283 | CORR=-0.008251
era 1140 저장 | rows=6,255 | CORR=-0.002192

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1141 저장 | rows=6,242 | CORR=0.003998
era 1142 저장 | rows=6,294 | CORR=-0.007883
era 1143 저장 | rows=6,322 | CORR=-0.014426

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1144 저장 | rows=6,333 | CORR=0.005509
era 1145 저장 | rows=6,293 | CORR=-0.005032
era 1146 저장 | rows=6,269 | CORR=-0.003669

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1147 저장 | rows=6,373 | CORR=-0.000963
era 1148 저장 | rows=6,310 | CORR=0.002091
era 1149 저장 | rows=6,168 | CORR=0.007047
era 1150 저장 | rows=6,135 | CORR=0.006492

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1151 저장 | rows=6,057 | CORR=0.012787
era 1152 저장 | rows=6,119 | CORR=0.014452
era 1153 저장 | rows=6,139 | CORR=0.008832

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1154 저장 | rows=6,155 | CORR=0.018143
era 1155 저장 | rows=6,208 | CORR=0.021872
era 1156 저장 | rows=6,298 | CORR=-0.002795

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1157 저장 | rows=6,442 | CORR=0.008840
era 1158 저장 | rows=6,493 | CORR=-0.005161
era 1159 저장 | rows=6,594 | CORR=-0.004559

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1160 저장 | rows=6,601 | CORR=-0.015222
era 1161 저장 | rows=6,505 | CORR=-0.009789
era 1162 저장 | rows=6,497 | CORR=-0.008326

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1163 저장 | rows=6,545 | CORR=0.012905
era 1164 저장 | rows=6,461 | CORR=0.013970
era 1165 저장 | rows=6,396 | CORR=0.001894

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1166 저장 | rows=6,304 | CORR=-0.001501
era 1167 저장 | rows=6,294 | CORR=0.001790
era 1168 저장 | rows=6,380 | CORR=0.008785

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1169 저장 | rows=6,418 | CORR=0.004370
era 1170 저장 | rows=6,455 | CORR=0.012091
era 1171 저장 | rows=6,554 | CORR=-0.005261
era 1172 저장 | rows=6,571 | CORR=0.007658

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1173 저장 | rows=6,608 | CORR=-0.000101
era 1174 저장 | rows=6,669 | CORR=-0.003436

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1175 저장 | rows=6,729 | CORR=-0.000968
era 1176 저장 | rows=6,706 | CORR=0.012311
era 1177 저장 | rows=6,697 | CORR=0.013543
era 1178 저장 | rows=6,587 | CORR=0.011927

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1179 저장 | rows=6,613 | CORR=0.013708
era 1180 저장 | rows=6,611 | CORR=-0.000439
era 1181 저장 | rows=6,681 | CORR=0.006408

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1182 저장 | rows=6,677 | CORR=0.012585
era 1183 저장 | rows=6,725 | CORR=0.026466

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1184 저장 | rows=6,712 | CORR=0.016361
era 1185 저장 | rows=6,696 | CORR=0.010308
era 1186 저장 | rows=6,762 | CORR=-0.001460

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1187 저장 | rows=6,862 | CORR=-0.010213
era 1188 저장 | rows=6,882 | CORR=-0.008622
era 1189 저장 | rows=6,915 | CORR=-0.004689

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1190 저장 | rows=6,902 | CORR=-0.010807
era 1191 저장 | rows=6,852 | CORR=0.000168
era 1192 저장 | rows=6,852 | CORR=-0.004070

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1193 저장 | rows=6,836 | CORR=-0.016258
era 1194 저장 | rows=6,806 | CORR=-0.009174
era 1195 저장 | rows=6,829 | CORR=0.002187

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1196 저장 | rows=6,812 | CORR=0.016661
era 1197 저장 | rows=6,758 | CORR=-0.000510
era 1198 저장 | rows=6,720 | CORR=-0.011661

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1199 저장 | rows=6,694 | CORR=-0.005286
era 1200 저장 | rows=6,658 | CORR=-0.022848
era 1201 저장 | rows=6,611 | CORR=-0.015317

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1202 저장 | rows=6,680 | CORR=-0.016021
era 1203 저장 | rows=6,734 | CORR=0.015461
era 1204 저장 | rows=6,857 | CORR=-0.006962

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1205 저장 | rows=6,991 | CORR=-0.019914
era 1206 저장 | rows=7,023 | CORR=-0.026831
era 1207 저장 | rows=7,127 | CORR=-0.027408

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1208 저장 | rows=7,126 | CORR=-0.004681
era 1209 저장 | rows=7,146 | CORR=0.018030
era 1210 저장 | rows=7,186 | CORR=0.015363

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1211 저장 | rows=7,212 | CORR=0.012017
era 1212 저장 | rows=7,231 | CORR=-0.005793
era 1213 저장 | rows=7,181 | CORR=0.010621

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1214 저장 | rows=7,060 | CORR=0.010569
era 1215 저장 | rows=7,008 | CORR=-0.006424

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1216 저장 | rows=6,979 | CORR=-0.024637
era 1217 저장 | rows=6,956 | CORR=-0.011592
era 1218 저장 | rows=6,961 | CORR=-0.009244

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(
/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1219 저장 | rows=7,001 | CORR=-0.000293
era 1220 저장 | rows=7,036 | CORR=0.000800
era 1221 저장 | rows=7,079 | CORR=-0.003909

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

era 1222 저장 | rows=7,105 | CORR=0.010082
era 1223 저장 | rows=7,102 | CORR=0.010783

/Library/Frameworks/Python.framework/Versions/3.14/lib/python3.14/site-packages/sklearn/utils/validation.py:2827: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(

         metric       value
0     mean_corr    0.010166
1      std_corr    0.013488
2        sharpe    0.753735
3  max_drawdown    0.188256
4          eras  649.000000

Diagnostics CSV: /Users/seomichelle/26-1 ESAA:Python/datasets/Numerai/diagnostics_v52/ridge_elastic_xgboost_v52_diagnostics.csv

In [20]:
# ============================================
# 17. 업로드 파일 최종 검사
# ============================================
diagnostics_check = pd.read_csv(DIAGNOSTICS_CSV)

print("shape:", diagnostics_check.shape)
print(diagnostics_check.head())
print(diagnostics_check["prediction"].describe())

assert diagnostics_check.columns.tolist() == ["id", "prediction"]
assert diagnostics_check["id"].is_unique
assert diagnostics_check["prediction"].notna().all()
assert diagnostics_check["prediction"].between(0, 1).all()

print("Diagnostics 업로드 형식 확인 완료")

shape: (4050241, 2)
                 id  prediction
0  n000101811a8a843    0.151645
1  n001e1318d5072ac    0.867668
2  n002a9c5ab785cbb    0.095136
3  n002ccf6d0e8c5ad    0.427754
4  n0041544c345c91d    0.099070
count    4.050241e+06
mean     5.000801e-01
std      2.886752e-01
min      1.368176e-04
25%      2.500804e-01
50%      5.000812e-01
75%      7.500795e-01
max      1.000000e+00
Name: prediction, dtype: float64
Diagnostics 업로드 형식 확인 완료

## 생성되는 주요 파일

### 전처리 객체
- `numerai_postprocess_v52/selected_features.json`
- `numerai_postprocess_v52/fitted_scaler.joblib`
- `numerai_postprocess_v52/fitted_pca.joblib`

### 캐시
- `cache_v52/train_pca_all.parquet`
- `cache_v52/train_final_cache.parquet`
- `cache_v52/val_final_cache.parquet`
- `pca500_lag1_lag2.parquet`
- `cache_v52/validation_pca_all.parquet`
- `cache_v52/validation_pca500_lag1_lag2.parquet`

### 모델 / 내부 예측
- `ridge_elastic_xgboost_stack_v52/base_ridge_model.joblib`
- `ridge_elastic_xgboost_stack_v52/base_elasticnet_model.joblib`
- `ridge_elastic_xgboost_stack_v52/base_xgboost_model.json`
- `ridge_elastic_xgboost_stack_v52/final_ridge_model.joblib`
- `ridge_elastic_xgboost_stack_v52/final_elasticnet_model.joblib`
- `ridge_elastic_xgboost_stack_v52/final_xgboost_model.json`
- `ridge_elastic_xgboost_stack_v52/final_meta_ridge_model.joblib`
- 각 모델의 `*_realtarget_val_predictions.csv`

### Numerai Diagnostics
- `diagnostics_v52/ridge_elastic_xgboost_v52_diagnostics.csv`
- `diagnostics_v52/ridge_elastic_xgboost_v52_per_era_corr.csv`
- `diagnostics_v52/ridge_elastic_xgboost_v52_local_summary.csv`

Scores 페이지의 플라스크 아이콘에는 `ridge_elastic_xgboost_v52_diagnostics.csv`를 업로드합니다.